Repository Azure/acs-engine, pull requests merged in 2018-04, with the labels that each got.

#2552 add timeout arg to retrycmd_if_failure in GPU install script
  examples/e2e-tests/kubernetes/gpu-enabled/definition.json
  pkg/acsengine/engine.go
Labels: in progress

#2086 Add documentation to update Route Table when Custom VNET is in different RG
  docs/custom-vnet.md
Labels: in progress

#2435 Specifying 256GB instead of 128 for etcd disk
  docs/clusterdefinition.md
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/api/types.go
Labels: in progress

#2577 timeout docker info command
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2575 make e2e compatible with jumpbox for private clusters
  parts/k8s/kubernetesmasterresources.t
  test/e2e/engine/template.go
  test/e2e/runner/cli_provisioner.go
Labels: in progress

#2593 Fix merge conflict in 1.7.16 for windows
  scripts/build-windows-k8s.sh
Labels: in progress

#2594 fixed nil o.OrchestratorVersion panic
  pkg/api/vlabs/validate.go
Labels: in progress

#2592 add Kubernetes v1.7.16 support
  pkg/acsengine/k8s_versions.go
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2584 Run kubelet outside container
  parts/k8s/artifacts/1.5/kuberneteskubelet.service
  parts/k8s/artifacts/kuberneteskubelet.service
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: in progress

#2603 k8s apiserver --oidc properties are user-overridable
  docs/clusterdefinition.md
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
Labels: in progress

#2605 Add support for k8s v1.8.11
  pkg/acsengine/k8s_versions.go
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2608 Fix merge conflict in windows 1.8.11
  scripts/build-windows-k8s.sh
Labels: in progress

#2610 Fix kubenet plugins
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2617 rename k8s custom script
  parts/k8s/kubernetescustomscript.sh
  pkg/acsengine/engine.go
Labels: in progress

#2618 fix maxPods deprecation inconsistency
  docs/clusterdefinition.md
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-maxpods.json
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
Labels: in progress, kind/bug

#2601 remove unnecessary setNetworkPlugin func
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#2622 Cluster definition docs cleanup
  docs/clusterdefinition.md
Labels: in progress

#2623 Remove old irrelevant comments about empty DNS prefix
  pkg/api/v20160930/validate.go
  pkg/api/v20170131/validate.go
Labels: in progress

#2625 retry apt-mark hold and apt-mark unhold
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#2630 remove deprecated etcd-quorum-read flag from apiserver
  docs/clusterdefinition.md
  pkg/acsengine/defaults-apiserver.go
Labels: in progress

#2638 add condition to kubelet.service to wait for kubelet bin
  parts/k8s/artifacts/kuberneteskubelet.service
Labels: in progress

#2640 update ubuntu image to 16.04.201804050
  parts/agentparams.t
  parts/masterparams.t
  pkg/acsengine/defaults.go
Labels: in progress

#2641 wait longer for cloud-init docker install
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: in progress

#2643 install kubelet deps during provisioning
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#2651 replace DCOS 1.9.0 with 1.9.8
  parts/dcos/dcoscustomdata198.t
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/types.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/convertertoapi.go
  pkg/api/v20170701/validate.go
Labels: in progress

#2581 [feature] Prevent overwriting existing cluster resources in output directories
  cmd/deploy.go
  docs/kubernetes/deploy.md
Labels: in progress

#2655 re-enable marathon app in DCOS cluster validation
  test/cluster-tests/dcos/test.sh
  test/e2e/dcos/dcos.go
  test/e2e/dcos/dcos_test.go
Labels: in progress

#2653 add Merge function for v20180331 to guard update scenario
  pkg/api/agentPoolOnlyApi/v20180331/merge.go
  pkg/api/agentPoolOnlyApi/v20180331/merge_test.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/apiloader.go
Labels: in progress

#2642 re-enable soak tests
  Makefile
  test/e2e/azure/cli.go
  test/e2e/azure/cli_test.go
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: awaiting review, in progress

#2654 Use latest patch of DefaultKubernetesRelease as default k8s version
  pkg/api/apiloader_test.go
  pkg/api/common/const.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/orchestrators.go
Labels: ready

#2660 Fix broken devenv.ps1 due to dot net core
  Dockerfile
Labels: in progress

#2650 Do not check for nodes Ready in CSE on masters
  .circleci/config.yml
  examples/kubernetes.json
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
  test/e2e/runner/cli_provisioner.go
Labels: in progress

#2667 E2E ILB test only create service once
  test/e2e/kubernetes/service/service.go
Labels: in progress

#2671 don't generate ssh key on existing cluster
  pkg/api/apiloader.go
Labels: in progress

#2648 Custom VNET API model.
  pkg/acsengine/testdata/agentPoolOnly/v20180331/agents.json
  pkg/api/agentPoolOnlyApi/v20180331/errors.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate_test.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
Labels: in progress

#2611 Add first cut of the OpenShift orchestrator
  .gitignore
  cmd/root.go
  examples/openshift.json
  parts/agentoutputs.t
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/openshiftmasterscript.sh
  parts/k8s/openshiftnodescript.sh
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/common/const.go
  pkg/api/common/versions.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/openshift/certgen/config.go
  pkg/openshift/certgen/doc.go
  pkg/openshift/certgen/files.go
  pkg/openshift/certgen/kubeconfig.go
  pkg/openshift/certgen/novalidate.go
  pkg/openshift/certgen/templates/master/etc/etcd/etcd.conf
  pkg/openshift/certgen/templates/master/etc/origin/master/htpasswd
  pkg/openshift/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/templates/master/etc/origin/master/scheduler.json
  pkg/openshift/certgen/templates/master/etc/origin/master/session-secrets.yaml
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/deploy-router.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/service-catalog.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/openshift/certgen/templates/node/etc/azure/azure.conf
  pkg/openshift/certgen/templates/node/etc/origin/node/node-dnsmasq.conf
  pkg/openshift/certgen/templates/node/etc/origin/node/resolv.conf
  pkg/openshift/certgen/templates/templates.go
  pkg/openshift/certgen/tls.go
  pkg/openshift/doc.go
  pkg/openshift/filesystem/filesystem.go
  scripts/validate-go.sh
Labels: in progress

#2672 add Kubernetes v1.10.1 support
  pkg/api/common/versions.go
Labels: in progress

#2664 allow specifying publisher, offer, and sku for windows images
  parts/dcos/dcosmastervars.t
  parts/windowsparams.t
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: in progress

#2676 CI test should invoke make build-cross
  .circleci/config.yml
Labels: in progress

#2532 Deploy customized Windows image for Kubernetes
  examples/windows/kubernetes-custom-image.json
  parts/k8s/kuberneteswinagentresourcesvmas.t
  pkg/api/vlabs/validate.go
Labels: DO-NOT-MERGE, in progress

#2677 restore DCOS 1.9.0
  parts/dcos/dcoscustomdata190.t
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/types.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/convertertoapi.go
  pkg/api/v20170701/validate.go
Labels: in progress

#2678 start commiting bindata file for openshift
  .gitignore
  pkg/openshift/certgen/files.go
  pkg/openshift/certgen/novalidate.go
  pkg/openshift/certgen/templates/bindata.go
  pkg/openshift/certgen/templates/templates.go
  scripts/validate-go.sh
Labels: orchestrator/openshift

#2686 fix clear containers cc-proxy
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#2544 Enable encryption at rest with Azure key vault
  .circleci/config.yml
  cmd/deploy.go
  docs/clusterdefinition.md
  examples/kubernetes-config/kubernetes-data-encryption-at-rest-with-external-kms.json
  parts/k8s/artifacts/kubernetesazurekms.service
  parts/k8s/artifacts/kuberneteskubelet.service
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/acsengine/addons.go
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/v20160930/types.go
  pkg/api/v20170131/types.go
  pkg/api/v20170701/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  test/e2e/engine/template.go
Labels: in progress

#2701 rationalize exit codes in CSE
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#2705 test encryption at rest w/ 1.10
  .circleci/config.yml
Labels: in progress

#2697 Generate openshift artifacts
  pkg/acsengine/defaults.go
  pkg/acsengine/output.go
Labels: orchestrator/openshift

#2704 use openshift_bootstrap_autoapprover to approve bootstrap CSRs
  parts/k8s/openshiftmasterscript.sh
  pkg/openshift/certgen/config.go
  pkg/openshift/certgen/kubeconfig.go
  pkg/openshift/certgen/templates/bindata.go
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-ocp-deploy.yml
Labels: orchestrator/openshift

#2699 enable prometheus metrics gathering with openshift-ansible playbooks
  parts/k8s/openshiftmasterscript.sh
  pkg/openshift/certgen/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-ocp-deploy.yml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/templates/master/tmp/bootstrapconfigs/master-config.yaml
Labels: orchestrator/openshift

#2713 rename cse k8s
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
Labels: in progress

#2712 Print age of soak cluster in test
  test/e2e/azure/cli.go
Labels: in progress

#2702 openshift certgen: use $GOPACKAGE and gofmt file
  pkg/openshift/certgen/templates/bindata.go
  pkg/openshift/certgen/templates/templates.go
Labels: orchestrator/openshift

#2717 fix the older api version to make LinuxProfile not required
  pkg/api/agentPoolOnlyApi/v20170831/types.go
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
Labels: in progress

#2721 Update references to gcr.io to point to Azure CDN endpoint
  docs/kubernetes/k8s-developers.md
  extensions/prometheus-grafana-k8s/v1/prometheus_values.yaml
  jenkins/Jenkinsfile.azure.kubernetes
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2723 Update doc for key vault encryption feat
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-keyvault-encryption.json
Labels: in progress

#2725 fix a bug where version is override when omitted during update
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/agentPoolOnlyApi/v20180331/merge.go
  pkg/api/apiloader.go
Labels: in progress

#2731 update Docker pause image for k8s 1.7
  pkg/acsengine/k8s_versions.go
Labels: in progress

#2733 fix nil pointer panic
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
Labels: in progress

#2734 Add support for k8s 1.9.7
  pkg/api/common/versions.go
Labels: in progress

#2740 Monitoring extension documentation addition
  docs/kubernetes/monitoring.md
Labels: kind/documentation

#2726 Fix private cluster feature doc
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-private-cluster-single-master.json
  examples/kubernetes-config/kubernetes-private-cluster.json
Labels: awaiting review, kind/documentation

#2718 Use ansible to deploy service catalog, ansible service broker, template service broker
  parts/k8s/openshiftmasterscript.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-ocp-deploy.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/service-catalog.yaml
Labels: orchestrator/openshift

#2719 Push unit test coverage results to codecov
  .circleci/config.yml
  .gitignore
  Makefile
  README.md
  scripts/ginkgo.coverage.sh
Labels: awaiting review, kind/chore

#2738 use global timeout for ILB E2E pod check
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2743 enable build windows zip for kubernetes 1.11 and up
  scripts/build-windows-k8s.sh
Labels: in progress

#2746 Moving openshift scripts to parts/openshift.
  parts/openshift/openshiftmasterscript.sh
  parts/openshift/openshiftnodescript.sh
  pkg/acsengine/engine.go
  pkg/openshift/certgen/templates/bindata.go
Labels: orchestrator/openshift

#2521 Update Calico to 3.1
  examples/networkpolicy/README.md
  examples/networkpolicy/kubernetes-calico.json
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
Labels: in progress

#2763 defaults rbac to false when omitted
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
Labels: in progress

#2620 VirtualMachineScaleSets support for Kubernetes
  docs/clusterdefinition.md
  examples/kubernetes-vmss/kubernetes.json
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  parts/k8s/kuberneteswindowssetup.ps1
  parts/masteroutputs.t
  pkg/acsengine/engine.go
  pkg/acsengine/testdata/disks-managed/kubernetes-vmss.json
  pkg/acsengine/testdata/largeclusters/kubernetes-vmss.json
  pkg/acsengine/testdata/windows/kubernetes-vmss.json
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: in progress

#2732 Fix kms encryption when kvsecretref is used
  pkg/acsengine/engine.go
Labels: in progress

#2737 Openshift deployments use only managed disks
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: orchestrator/openshift

#2776 Fixed the default DCOS version in v20170701 to 1.9.0 and removed unsu…
  pkg/api/convertertoapi.go
Labels: in progress

#2770 add node labels arg to windows setup script
  parts/k8s/kuberneteswindowssetup.ps1
Labels: in progress

#2764 normalizeazureregion added in scale, upgrade, and deploy
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoapi.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: in progress

#2695 Add separate nsg for the router
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
Labels: orchestrator/openshift

#2800 rev go-dev image to version 1.10
  .circleci/config.yml
  Makefile
Labels: in progress

#2794 Add support for Kubernetes v1.10.2
  pkg/api/common/versions.go
Labels: in progress

#2801 enable cleanup script to continue despite errors
  test/e2e/cleanup.sh
Labels: in progress

#2806 add os type to clusterdefinition.md
  docs/clusterdefinition.md
Labels: area/docs, in progress, kind/documentation

#2807 Add crd ciliumendpoints.cilium.io to cilium clusterrole
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
Labels: in progress

#2756 Add etcd encryption key
  docs/clusterdefinition.md
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: in progress

#2782 Add acs-engine version information to acs-engine provisioned k8s clusters (masters and agents)
  cmd/deploy.go
  cmd/generate.go
  cmd/scale.go
  cmd/upgrade.go
  docs/kubernetes/deploy.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/masterparams.t
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: cse-sync-week, in progress
