Repository Azure/acs-engine, pull requests merged in 2018-12, with the labels that each got.

#3999 Add kubelet system-reserved on Windows
  pkg/api/defaults-kubelet.go
Labels: do-not-merge/hold, in progress, size/XS

#4323 Bump VHD version to 2018.11.28
  pkg/api/azenvtypes.go
Labels: in progress

#4198 Add test for docker based workflow (ContainerInventory)
  pkg/api/addons.go
  pkg/api/defaults_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: size/XS

#4335 Add aks-engine redirection notice to front page README
  README.md
Labels: in progress

#4333 Use 2018.12.03 VHD images
  pkg/api/azenvtypes.go
Labels: in progress

#4346 [BUG] orchestratorVersion should not get changed for ACS scale apiVersion 2017-07-01
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
Labels: in progress, kind/bug

#4361 Enable Azure CNI 1.0.15
  pkg/api/azenvtypes.go
  pkg/api/const.go
Labels: in progress

#4362 Clarify that this is no longer an active repo
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/developers.md
  docs/roadmap/planning-process.md
  docs/roadmap/releases.md
Labels: in progress
