Repository Azure/acs-engine, pull requests merged in 2018-03, with the labels that each got.

#2363 update docs for private cluster
  docs/kubernetes/features.md
Labels: in progress

#2364 Remove 1.6.x upgrade tests.
  examples/k8s-upgrade/v1.6.11.json
  examples/k8s-upgrade/v1.6.11.json.env
  examples/k8s-upgrade/v1.6.13.json
  examples/k8s-upgrade/v1.6.13.json.env
  examples/k8s-upgrade/v1.7.7.json
  examples/k8s-upgrade/v1.8.4.json
  test/acse-conf/acse-upgrade-lnx.json
Labels: in progress

#2369 Add k8s 1.7.13 support
  cmd/orchestrators_test.go
  examples/k8s-upgrade/README.md
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/v20170930/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: awaiting review

#2370 Resolve merge conflict in building 1.7.13
  scripts/build-windows-k8s.sh
Labels: in progress

#2339 metrics server addon
  parts/k8s/addons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/k8s_versions.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2379 minor fix in build script
  scripts/build-windows-k8s.sh
Labels: in progress

#2391 remove unnecessary hyperkube reference
  docs/kubernetes/features.md
Labels: area/docs, in progress

#2365 Remove deprecated '--require-kubeconfig' for k8s
  parts/k8s/artifacts/kuberneteskubelet.service
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/acsengine/engine.go
Labels: in progress

#2396 add etcd certs to KV docs
  examples/keyvault-params/README.md
Labels: awaiting review, ready

#2397 Update default tiller version to 2.8.1
  pkg/acsengine/const.go
Labels: awaiting review, kind/chore, orchestrator/k8s, size/small

#2394 Deprecate k8s 1.5.x
  examples/k8s-upgrade/README.md
  examples/kubernetes-releases/kubernetes1.5.json
  examples/scale-up/kubernetes_orignal_params.json
  examples/scale-up/kubernetes_scale_up_params.json
  parts/k8s/addons/1.5/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.5/kubernetesmasteraddons-tiller-deployment.yaml
  pkg/acsengine/defaults-kubelet_test.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/k8s_versions.go
  pkg/api/apiloader_test.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/convertertoapi.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  test/acse-conf/acse-feature-validation.json
  test/e2e/kubernetes-deployments.json
Labels: ready

#2225 blocking cse on cluster nodes ready
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
Labels: in progress

#2402 test single master node Windows clusters
  examples/e2e-tests/kubernetes/windows/definition.json
Labels: in progress

#2406 update component versions for v0.14.0
  .circleci/config.yml
  Makefile
  parts/agentparams.t
  parts/masterparams.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
Labels: orchestrator/k8s

#2401 auto-jumpbox provisioning for private clusters
  docs/clusterdefinition.md
  docs/kubernetes/features.md
  examples/e2e-tests/kubernetes/kubernetes-config/private-cluster-single-master.json
  examples/e2e-tests/kubernetes/kubernetes-config/private-cluster.json
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: awaiting review, in progress

#2415 Kubernetes v1.9 clusters use addon-resizer 1.7
  pkg/acsengine/k8s_versions.go
Labels: in progress

#2416 chore(README): Remove managed disks private preview notice
  README.md
Labels: in progress

#2413 Add Kubernetes 1.10-beta.2 support
  .circleci/config.yml
  pkg/acsengine/defaults.go
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/orchestrators_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2426 rationalize "is greater than 1.9" implementation to deal with 1.10-beta*
  pkg/acsengine/addons.go
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/common/helper.go
  pkg/api/types.go
Labels: in progress, orchestrator/k8s

#2414 Jumpbox kubeconfig
  parts/k8s/kubeconfig.json
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/engine.go
Labels: awaiting review

#2439 add retries to systemctl calls
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  pkg/acsengine/engine.go
Labels: in progress

#2444 don’t restart systemctl where it is already set to Restart=on-failure
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2449 Revert "don’t restart systemctl where it is already set to Restart=on-failure"
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2450 Revert "add retries to systemctl calls"
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  pkg/acsengine/engine.go
Labels: in progress

#2451 Revert "Jumpbox kubeconfig"
  parts/k8s/kubeconfig.json
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/engine.go
Labels: in progress

#2429 network policy: add cilium
  docs/clusterdefinition.md
  docs/kubernetes/deploy.md
  docs/kubernetes/features.md
  examples/networkpolicy/kubernetes-cilium.json
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes-deployments.json
Labels: in progress

#2455 Jumpbox kubeconfig second attempt
  parts/k8s/kubeconfig.json
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/engine.go
Labels: in progress

#2458 orchestratorRelease by platform in vlabs
  pkg/api/common/const.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/convertertoapi.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/dcos/dcos_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2405 Kubernetes v1.9.4 support
  examples/k8s-upgrade/v1.8.4.json.env
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: DO-NOT-MERGE, in progress, orchestrator/k8s

#2441 Add support for k8s 1.8.9
  examples/k8s-upgrade/README.md
  examples/k8s-upgrade/v1.7.9-hybrid.json.env
  examples/k8s-upgrade/v1.7.9-win.json.env
  examples/k8s-upgrade/v1.7.9.json.env
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2442 Add support for k8s 1.7.14
  cmd/orchestrators_test.go
  examples/k8s-upgrade/README.md
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/v20170930/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: in progress

#2433 simplify code and turn on more linters
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/transform/transform.go
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/common/const_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/v20160330/validate.go
  pkg/api/v20160930/validate.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/graph.go
  pkg/armhelpers/mockclients.go
  pkg/operations/cordondrainvm.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrademasternode.go
  pkg/operations/kubernetesupgrade/upgrader.go
  scripts/validate-go.sh
  test/acs-engine-test/main.go
  test/acs-engine-test/promote/promote.go
  test/acs-engine-test/report/report.go
  test/acs-engine-test/report/report_test.go
  test/e2e/config/config.go
  test/e2e/dcos/dcos.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
  test/e2e/remote/ssh.go
  test/e2e/runner/cli_provisioner.go
Labels: in progress

#2440 added hcp 20180331 api model to support addon
  pkg/api/agentPoolOnlyApi/v20180331/const.go
  pkg/api/agentPoolOnlyApi/v20180331/doc.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/agentPoolOnlyApi/v20180331/types_test.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/apiloader.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/types.go
Labels: in progress

#2467 goimports: run on files
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi_test.go
Labels: in progress

#2437 Deregister node in api server during cordon-and-drain
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/kubeclient.go
  pkg/armhelpers/mockclients.go
  pkg/operations/cordondrainvm.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
Labels: in progress

#2466 added deployment name and resource group name to deployment error
  pkg/armhelpers/deploymentError.go
Labels: in progress

#2470 fix tests for k8s 1.10 upgrade
  pkg/api/orchestrators_test.go
Labels: in progress

#2469 decrease timeout for ILB test
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2468 fix azuredeploy warnings
  parts/dcos/dcosWindowsAgentResourcesVmas.t
  parts/dcos/dcosagentresourcesvmas.t
  parts/dcos/dcosmasterresources.t
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/swarm/swarmagentresourcesvmas.t
  parts/swarm/swarmmasterresources.t
  parts/swarm/swarmwinagentresourcesvmas.t
  pkg/acsengine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/acsengine/transform/transformtestfiles/dcos_scale_template.json
  pkg/acsengine/transform/transformtestfiles/dcos_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_template.json
Labels: awaiting review

#2477 fix jumpbox custom vnet missing variables
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#2472 Kubernetes 1.10.0-beta.4
  .circleci/config.yml
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: in progress

#2479 pull hyperkube image before systemctl kubelet
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#2471 Windows support for Kubernetes v1.7.14, v1.8.9, and v1.9.4
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/vlabs/validate_test.go
  scripts/build-windows-k8s.sh
Labels: in progress

#1137 private registry support for DCOS
  docs/images/acrblade.png
  docs/images/dcos-add-file-json.png
  docs/images/dcos-create-service-from-reg.png
  docs/images/dcos-create-service-json.png
  docs/images/dcos-create-service.png
  docs/images/dcos-running-service-from-reg-files.png
  docs/images/dcos-running-service-from-reg.png
  examples/dcos-private-registry/README.md
  examples/dcos-private-registry/dcos.json
  parts/agentparams.t
  parts/dcos/dcosagentvars.t
  parts/dcos/dcoscustomdata184.t
  parts/dcos/dcoscustomdata187.t
  parts/dcos/dcoscustomdata188.t
  parts/dcos/dcoscustomdata190.t
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: area/engine, area/templates, awaiting review, in progress, needs rebase, orchestrator/dcos, waiting for ci

#2360 Change k8s default version to 1.8.9
  pkg/api/common/const.go
Labels: DO-NOT-MERGE, in progress, needs rebase

#2483 Remove unnecessary etcd systemd Alias directive
  parts/k8s/kubernetesmastercustomdata.yml
Labels: kind/bug, orchestrator/k8s

#2487 Kubernetes v1.9.5 support
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2488 Add Kubernetes v1.8.10 support
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2457 add timeout to restart docker
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2490 Add Kubernetes v1.7.15 support
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2486 retry funcs in a common place
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesmastergenerateproxycertscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/engine.go
Labels: in progress

#2492 cloud-init: provision script hygiene
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2497 Add Kubernetes v1.10.0-rc.1 support
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2493 modify build script
  scripts/build-windows-k8s.sh
Labels: in progress

#2498 totalNodes var and params are not IsHostedMaster
  parts/k8s/kubernetesmastervars.t
Labels: in progress, kind/bug, orchestrator/k8s

#2505 Kubernetes v1.9.6
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2501 fixed dcos deployment generation with omitted preprovisioning script
  parts/dcos/dcosagentvars.t
Labels: in progress

#2500 Generic kube-scheduler config interface
  docs/clusterdefinition.md
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
  pkg/acsengine/defaults-scheduler.go
  pkg/acsengine/defaults-scheduler_test.go
  pkg/acsengine/defaults.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: in progress

#2515 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#2506 Make handling Kubernetes versions easier
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults-kubelet_test.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/k8s_versions.go
  pkg/api/apiloader_test.go
  pkg/api/common/const.go
  pkg/api/common/const_test.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/api/v20170930/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: in progress, orchestrator/k8s

#2518 add timeout to retry func, deal with curl + tar
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesmastergenerateproxycertscript.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: in progress

#2528 Move some AAD args out of the static list
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
Labels: in progress

#2530 remove reference to deprecated const
  pkg/acsengine/defaults-apiserver_test.go
Labels: in progress

#2520 move sed to kubelet.sh, remove unnecessary exit 0
  parts/k8s/kubernetesagentcustomdata.yml
Labels: in progress

#2533 Add Kubernetes v1.10.0 support
  pkg/api/common/versions.go
Labels: in progress

#2536 use cri-containerd not cri-o
  examples/e2e-tests/kubernetes/kubernetes-config/clear-containers.json
  examples/kubernetes-clear-containers.json
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2539 clear-containers: cleanup some leftover options
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2499 enable building windows 1.10 zip
  .circleci/config.yml
  pkg/api/common/versions.go
  pkg/api/vlabs/validate_test.go
  scripts/build-windows-k8s.sh
Labels: in progress

#2547 containerd: just install tarball release
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2543 Fix version comparison
  parts/k8s/kuberneteswindowssetup.ps1
Labels: in progress

#2531 add Istio example
  examples/service-mesh/README.md
  examples/service-mesh/istio.json
Labels: ready

#2519 Add containerized flag and update mount options
  parts/k8s/artifacts/kuberneteskubelet.service
Labels: in progress

#2546 Make --azure-container-registry-config optional
  docs/clusterdefinition.md
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
Labels: in progress
