Repository Azure/acs-engine, pull requests merged in 2018-10, with the labels that each got.

#3927 removed duplication of shellQuote function and added test cases.
  pkg/acsengine/template_generator.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, in progress, lgtm, size/L

#3928 Change 'windowsVersion' to 'imageVersion' in docs
  docs/kubernetes/windows-details.md
Labels: size/XS

#3934 Add support for Kubernetes 1.9.11
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3924 Simplify some upgrader version cases
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, lgtm, size/S

#3940 Use `echo -n` to skip adding newline to external command output
  pkg/helpers/helpers_test.go
Labels: approved, lgtm, size/XS

#3936 Add warning message for VMSS master deployments
  docs/clusterdefinition.md
  pkg/api/vlabs/validate.go
Labels: approved, in progress, lgtm, size/XS

#3942 Add Kubernetes 1.12.0 to VHD image
  packer/install-dependencies.sh
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3938 Migrating Get Addon By Name and Get Container Index By Name methods
  pkg/acsengine/addons.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/acsengine/params_k8s.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/L

#3943 Fix accidentally shadowed variable in upgrade cluster.
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, kind/bug, lgtm, priority/P0, size/XS

#3939 Docs Docs Docs! Adding windowsAgent apimodel parameters
  docs/clusterdefinition.md
Labels: approved, in progress, lgtm, size/M

#3944 Change default value for osImageVersion parameter
  parts/masterparams.t
Labels: approved, in progress, lgtm, size/XS

#3918 Add support for Kubernetes 1.12.0
  packer/install-dependencies.sh
  parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-metrics-server-deployment.yaml
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/api/common/versions.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, kind/chore, lgtm, orchestrator/k8s, size/L

#3916 ip-masq-agent as addon
  parts/k8s/addons/ip-masq-agent.yaml
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/artifacts.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/L

#3949 Update AKS base image to 0.17.0
  pkg/acsengine/defaults.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3948 Move utility methods to the helper package
  cmd/dcos-upgrade.go
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/output.go
  pkg/acsengine/ssh.go
  pkg/acsengine/ssh_test.go
  pkg/helpers/filesaver.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
  pkg/helpers/pki.go
  pkg/helpers/pki_test.go
Labels: approved, in progress, lgtm, size/L

#3954 Update how legacy E2E test runner determines pre-existing resource group
  test/common.sh
Labels: approved, in progress, lgtm, size/XS

#3957 add basic distro unit tests for swarm, swarmmode, dcos
  pkg/acsengine/defaults_test.go
Labels: approved, in progress, lgtm, size/S

#3947 Update go-dev tools image for go 1.11.1
  .circleci/config.yml
  Makefile
  makedev.ps1
Labels: approved, in progress, kind/chore, size/XS

#3925 Refactor VM prefix to template functions
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/template_generator.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/L

#3908 Accelerated networking for Windows
  docs/clusterdefinition.md
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/acsengine/defaults.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, lgtm, size/L, windows

#3963 Add support for Kubernetes 1.12.1
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3964 Cleanup Packer directory after VHD build
  packer/vhd-image-builder.json
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, size/S

#3965 Fix install hyperkube
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/XS

#3966 retain existing AKS SNAT implementation
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/params_k8s.go
Labels: approved, in progress, size/S

#3915 create cgroups needed by kubelet's --system-reserved and --kube-reserved flags
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/system.conf
  pkg/acsengine/const.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/M

#3950 Dont set default distro when OSType is Windows
  pkg/acsengine/defaults.go
Labels: approved, lgtm, size/XS

#3970 missing systemConf var in vmss
  parts/k8s/kubernetesmastervarsvmss.t
Labels: approved, in progress, kind/bug, lgtm, size/XS

#3969 update AKS VHD image to ver 0.18.0
  pkg/api/azenvtypes.go
Labels: approved, in progress, size/XS

#3973 Fix urls to gofi.sh
  docs/acsengine.md
Labels: approved, lgtm, size/XS

#3972 Strengthen unit tests for cluster ID
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, do-not-merge/hold, in progress, lgtm, size/M

#3971 optimize customData payload by removing comments
  parts/k8s/addons/1.10/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/addons/kubernetesmaster-audit-policy.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/health-monitor.sh
  parts/k8s/kubernetes_mountetcd.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesprovisionsource.sh
  parts/k8s/manifests/kubernetesmaster-pod-security-policy.yaml
  parts/k8s/system.conf
Labels: approved, in progress, lgtm, size/L

#3946 Set default Kubernetes version (Linux) to 1.10
  pkg/api/common/const.go
Labels: approved, in progress, lgtm, size/XS

#3978 Using local rand object to generate cluster ids
  pkg/api/types.go
Labels: approved, in progress, lgtm, size/XS

#3980 Update node-labels to 1.6+ standard
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/XS

#3981 E2E: retry kubectl delete job
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/M

#3982 E2E: actually fail when no InternalIP, ssh master tweaks, delete retries
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
Labels: approved, in progress, lgtm, size/L

#3987 1.12 uses coredns
  parts/k8s/addons/coredns.yaml
  parts/k8s/addons/dns-autoscaler.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesparams.t
  pkg/acsengine/artifacts.go
  pkg/acsengine/const.go
  pkg/acsengine/params_k8s.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/validate-dns.yaml
Labels: approved, in progress, size/L

#3974 Refactor: Moving set defaults logic from package acsengine to package api
  cmd/deploy.go
  cmd/generate.go
  cmd/scale.go
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/output.go
  pkg/acsengine/output_test.go
  pkg/acsengine/params.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/types.go
  pkg/api/addons.go
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoapi.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-cloud-controller-manager.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-kubelet.go
  pkg/api/defaults-kubelet_test.go
  pkg/api/defaults-openshift-certs.go
  pkg/api/defaults-scheduler.go
  pkg/api/defaults-scheduler_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/mocks.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/helpers/Get-AzureConstants.py
  pkg/helpers/azureconst.go
  pkg/helpers/helpers_test.go
  pkg/helpers/pki_test.go
  pkg/openshift/certgen/certgen.go
  pkg/openshift/certgen/release39/defaults.go
  pkg/openshift/certgen/unstable/defaults.go
  pkg/operations/dcosupgrade/upgrader.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrader.go
  test/acs-engine-test/main.go
Labels: approved, in progress, lgtm, size/XXL

#3983 Enable the kubelet-monitor systemd unit
  parts/k8s/kubernetesconfigs.sh
Labels: approved, in progress, lgtm, size/XS

#3991 E2E: k8s component tests should happen before api tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/L

#3992 add kubernetes1.12 example
  examples/kubernetes-releases/kubernetes1.12.json
Labels: approved, in progress, lgtm, size/M

#3993 gosimple fixes
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/XS

#3989 Azure CNI v1.0.12
  pkg/api/const.go
Labels: approved, do-not-merge/hold, in progress, size/XS

#3975 bump etcd version
  packer/install-dependencies.sh
  pkg/api/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, needs rebase, size/XS

#3995 revert swarmm change
  parts/swarm/swarmmastervars.t
Labels: approved, in progress, lgtm, size/XS

#3909 Update apiversion to make it consistent in k8s templates
  docs/custom-vnet.md
  docs/extensions.md
  extensions/choco/v1/template-link.json
  extensions/hello-world-k8s/v1/template-link.json
  extensions/microsoft-oms-agent-k8s/v1/template-link.json
  extensions/microsoft-oms-agent-k8s/v1/template.json
  extensions/prometheus-grafana-k8s/v1/template-link.json
  extensions/windows-patches/v1/template-link.json
  extensions/winrm/v1/template-link.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, in progress, lgtm, size/L

#3997 E2E: set stability iterations to 10 by default
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/S

#4004 Update kube-dns 1.14.13 for k8s 1.8 through 1.11
  pkg/api/k8s_versions.go
Labels: approved, in progress, lgtm, size/S

#4005 update kubernetes-dashboard to 1.10
  pkg/api/k8s_versions.go
Labels: approved, in progress, lgtm, size/S

#4014 only schedule coredns pods on a linux node
  parts/k8s/addons/coredns.yaml
Labels: approved, do-not-merge/hold, in progress, size/XS

#3998 add coredns image reference to components versions map
  parts/k8s/kubernetesparams.t
  pkg/acsengine/params_k8s.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
Labels: approved, in progress, size/M

#4028 health-monitor script doesn’t require docker
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
Labels: approved, in progress, lgtm, size/L

#4015 Updating the tag for omsagent container to use the latest production tag
  pkg/api/addons.go
Labels: approved, lgtm, size/XS

#4026 Replace aad-pod-identity docker image with official MS container registry
  parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
Labels: approved, lgtm, size/XS

#4031 Fix linter errors reported by gosimple
  pkg/api/defaults_test.go
Labels: approved, in progress, kind/chore, lgtm, size/S

#3994 Split Windows setup scripts, prepare for cleanup and multiple CRI
  docs/clusterdefinition.md
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsazurecnifunc.ps1
  parts/k8s/windowscnifunc.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/XXL

#4033 keyvault-flexvolume image version bump
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
Labels: approved, in progress, lgtm, size/XS

#4017 Doc style, minor updates pass
  README.md
  docs/acsengine.md
  docs/kubernetes/deploy.md
  docs/kubernetes/walkthrough.md
Labels: approved, lgtm, size/L

#4039 Fix typo in prometheus-grafana-k8s extension
  extensions/prometheus-grafana-k8s/v1/template-link.json
Labels: approved, lgtm, size/XS

#4040 Add support for Kubernetes 1.10.9
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, size/XS

#4036 Add support for Kubernetes v1.13.0-alpha.1
  .circleci/config.yml
  pkg/api/common/versions.go
  pkg/api/k8s_versions.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, lgtm, size/L

#4048 Fix the Authorization and ManagedIdentity api versions
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, in progress, lgtm, size/M

#4049 schedule ip-masq-agent on masters
  parts/k8s/addons/ip-masq-agent.yaml
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/nginx-master.yaml
Labels: approved, in progress, lgtm, size/M

#4050 delay docker and kubelet health monitors for 30 mins
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
Labels: approved, in progress, size/M

#4056 Don't block on Kubernetes installation cleanup operations
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/XS

#4054 update to AKS VHD image 0.19.0
  pkg/api/azenvtypes.go
Labels: approved, in progress, lgtm, size/XS

#4058 set default masterSubnet value for custom VNET
  parts/masterparams.t
Labels: approved, in progress, lgtm, size/XS

#4059 Updating oms agent tag to use the latest tag released
  pkg/api/addons.go
Labels: approved, lgtm, size/XS

#4061 Don't test k8s 1.8 or 1.9 in CircleCI
  .circleci/config.yml
Labels: approved, in progress, lgtm, size/L

#4067 Azure CNI 1.0.12 should be in VHD image
  packer/install-dependencies.sh
Labels: approved, in progress, lgtm, size/XS

#4068 use 16.04-LTS:latest by default for Ubuntu distro flows
  pkg/api/azenvtypes.go
Labels: approved, in progress, lgtm, size/XS

#4062 E2E: enable pod-svc connection test
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/runner/ginkgo.go
Labels: approved, in progress, size/M

#4073 E2E: reuse long-running apache pod, HPA stabilization
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/L

#4072 Update doc: keyvault-flexvol addon default flag
  docs/clusterdefinition.md
Labels: approved, in progress, lgtm, size/XS

#4074 AKS VHD: aks-ubuntu-1604-201810 2018.10.18
  pkg/api/azenvtypes.go
Labels: approved, in progress, lgtm, size/XS

#4079 E2E: general hardening
  test/e2e/kubernetes/hpa/hpa.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
Labels: approved, in progress, size/L

#4087 E2E: test HPA scale down as well
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress, size/M

#4085 remove unused nsg for AKS
  parts/k8s/kubernetesbase.t
Labels: approved, in progress, lgtm, size/XS

#4084 Fix issue where kubernetesDashboard params weren't being added despite e enabling the dashboard addon
  pkg/acsengine/params_k8s.go
  pkg/acsengine/params_k8s_test.go
  pkg/api/mocks.go
Labels: approved, in progress, lgtm, size/L

#3905 set FailureActions for docker, kubelet, kubeproxy on windows
  parts/k8s/kuberneteswindowssetup.ps1
Labels: lgtm, size/S

#4082 Update vmss master EncryptionWithExternalKms with userassignedidentity
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervarsvmss.t
Labels: approved, in progress, lgtm, size/M

#4094 update azure-npm to v1.0.13
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
Labels: approved, size/XS

#4081 CSE apt lock hygiene
  parts/k8s/kubernetesprovisionsource.sh
  parts/k8s/setup-custom-search-domains.sh
Labels: approved, in progress, lgtm, size/S

#4099 use azk8s.cn instead of akscn.io for azure china
  pkg/api/azenvtypes.go
Labels: lgtm, size/S

#4097 enable user-configurable Azure CNI URL
  pkg/acsengine/params_k8s.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/M

#4100 Don't require vm tags
  cmd/scale.go
  cmd/upgrade.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  test/e2e/runner/ginkgo.go
Labels: approved, in progress, lgtm, size/L

#3896 Moby container runtime
  .vsts-ci.yaml
  docs/clusterdefinition.md
  packer/feature-flagged.sh
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  parts/k8s/kubernetesparams.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/params_k8s.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/k8s_versions.go
  pkg/api/k8s_versions_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, size/L

#4112 minor template optimization in kubernetesmastervarsvmss.t
  parts/k8s/kubernetesmastervarsvmss.t
Labels: approved, in progress, size/XS

#4117 Fix potential nil pointer dereference when VM tags are empty
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, kind/bug, lgtm, size/XS

#4113 add resilience to nvidia driver install/config
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, size/M

#4121 don’t timeout for apt
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, size/S

#4114 Make --profiling user configurable
  pkg/api/const.go
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-apiserver_test.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-controller-manager_test.go
  pkg/api/defaults-scheduler.go
  pkg/api/defaults-scheduler_test.go
Labels: approved, in progress, lgtm, size/L

#4123 suppressing sensitive openssl output
  parts/k8s/kubernetesmastergenerateproxycertscript.sh
Labels: approved, lgtm, size/XS

#4119 Configure Docker Version on Windows Nodes
  examples/windows/kubernetes-windows-docker-version.json
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowsconfigfunc.ps1
  parts/windowsparams.t
  pkg/acsengine/params.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#4127 disable kubelet health monitor
  parts/k8s/kubernetesconfigs.sh
Labels: approved, size/S

#4128 Add support for Kubernetes v1.13.0-alpha.2
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#4130 Add support for Kubernetes 1.11.4
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, kind/chore, lgtm, size/XS

#4131 Add support for Kubernetes 1.12.2
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, size/XS

#4092 Add external custom yaml for manifests
  docs/clusterdefinition.md
  examples/addons/custom-manifests/kubernetes-custom-manifests.json
  pkg/acsengine/artifacts.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/testdata/addons/kubernetes-custom-psp.json
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, size/L

#4120 add AKSDockerEngine distro
  pkg/api/azenvtypes.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/L

#4141 Adding DOCKER_API_VERSION workaround
  parts/k8s/windowsconfigfunc.ps1
Labels: in progress, lgtm, size/S

#4145 restore exechealthz references
  pkg/api/k8s_versions.go
Labels: approved, in progress, lgtm, size/XS

#4133 Enable k8s features by default
  pkg/api/defaults-apiserver.go
  pkg/api/defaults-controller-manager.go
  pkg/api/defaults-controller-manager_test.go
Labels: in progress, size/M

#4104 Optimize CSE + FeatureFlags option for run in background
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#4146 add VHD images w/ k8s 1.11.4 and k8s 1.12.2
  pkg/api/azenvtypes.go
Labels: approved, in progress, lgtm, size/XS

#4137 use china mirror in binary downloading on azure china
  pkg/api/azenvtypes.go
Labels: approved, lgtm, size/S

#4103 Make windows binary url configurable
  docs/clusterdefinition.md
  docs/design/proposed-template-refactor.md
  parts/k8s/kubernetesbase.t
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
  parts/k8s/windowskubeletfunc.ps1
  pkg/acsengine/params.go
  pkg/acsengine/params_test.go
  pkg/acsengine/testdata/windows/kubernetes-kubernetesconfig.json
  pkg/acsengine/types.go
  pkg/api/azenvtypes.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#4032 Move the role assignment to the ARM template and fix api versions
  cmd/deploy.go
  examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas-multimaster.json
  examples/e2e-tests/userassignedidentity/vmas/kubernetes-vmas.json
  examples/e2e-tests/userassignedidentity/vmss/kubernetes-vmss.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  pkg/acsengine/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress, size/L
