Repository Azure/acs-engine, pull requests merged in 2018-06, with the labels that each got.

#2859 Scaling Windows agent pools for Availability Sets and VMSS
  cmd/scale.go
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, lgtm, size/M

#3127 Heapster Service missing from addon and is breaking dashboard charts
  parts/k8s/addons/kubernetesmasteraddons-heapster-deployment.yaml
Labels: approved, lgtm, size/S

#3100 Replacing the static pod definition for etcd ip.
  parts/openshift/unstable/openshiftmasterscript.sh
  pkg/acsengine/engine.go
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-ocp-deploy.yml
Labels: approved, lgtm, size/S

#3053 Version artifacts gathering in openshift e2e
  .circleci/config.yml
  test/e2e/openshift/util/util.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/L

#3083 Check outbount connection at the start of CSE
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3116 Replace log.Fatal by return errors in deploy.go
  cmd/deploy.go
  cmd/deploy_test.go
Labels: approved, in progress, lgtm, size/M

#3084 light refactor of engine.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/acsengine/params.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/pki_test.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/types.go
Labels: in progress, size/XXL

#3137 Fixing the version test for unstable.
  test/e2e/openshift/openshift_test.go
Labels: approved, lgtm, orchestrator/openshift, size/XS

#3145 Add support for k8s 1.9.8
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3135 Strip k8s version to Major.Minor.Build format
  parts/k8s/kuberneteswindowssetup.ps1
Labels: approved, lgtm, size/XS

#3147 Merge AADProfile during update
  pkg/api/agentPoolOnlyApi/v20180331/merge.go
Labels: approved, in progress, lgtm, size/XS

#3138 Feat/custom dns
  docs/clusterdefinition.md
  examples/vnet/kubernetesvnet-customnodesdns.json
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/params.go
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#3146 Kubernetes: working calico E2E
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/networkpolicy/networkpolicy.go
  test/e2e/kubernetes/workloads/calico-policy.yaml
Labels: in progress, size/M

#3144 add support for k8s 1.11.0-beta.1
  .circleci/config.yml
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/M

#3148 chore(E2E) flaky calico networkpolicy delete
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress, size/XS

#3156 Simplify error handling in rollout test
  test/e2e/openshift/openshift_test.go
  test/e2e/openshift/util/util.go
Labels: approved, in progress, lgtm, size/S

#3159 Fix test-style broken since bcf7d3b
  test/e2e/kubernetes/kubernetes_test.go
Labels: size/XS

#3152 Get kubeconfig in e2e as early as possible
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, lgtm, size/XS

#3160 Drop redundant prowjob namespace
  .prowci/config.yaml
Labels: approved, in progress, lgtm, size/XS

#3118 acs-engine orchestrators should throw an error when an invalid/unsup…
  pkg/api/common/const.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: size/L

#3165 Sort k8s versions for better error message readability
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3142 add chinaeast2 and chinanorth2
  pkg/acsengine/Get-AzureConstants.py
  pkg/acsengine/azureconst.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/engine.go
  pkg/acsengine/pki_test.go
  test/acs-engine-test/main.go
Labels: in progress, size/L

#3172 Add more debug log in the router test
  test/e2e/openshift/util/util.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#2762 Provisioning of custom files when deploying k8s cluster
  docs/clusterdefinition.md
  examples/customfiles/README.md
  examples/customfiles/kubernetes-customfiles-podnodeselector.json
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/acsengine/customfiles.go
  pkg/acsengine/customfiles_test.go
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#3173 openshift: infra nic depends on router lb
  parts/k8s/kubernetesagentresourcesvmas.t
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#3169 openshift: increase loglevel for control plane components
  parts/openshift/release-3.9/openshiftmasterscript.sh
  parts/openshift/release-3.9/openshiftnodescript.sh
  parts/openshift/unstable/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftnodescript.sh
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/master/etc/etcd/etcd.conf
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/etc/etcd/etcd.conf
Labels: approved, in progress, lgtm, orchestrator/openshift, size/S

#3154 Move artifacts gathering around
  test/e2e/openshift/openshift_test.go
  test/e2e/openshift/util/util.go
  test/e2e/runner.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/M

#3177 DCOS: remove obsolete Windows provisioning dependencies
  parts/dcos/dcosWindowsProvision.ps1
Labels: in progress, size/XS

#3180 Kubernetes: update Azure CNI to v1.0.6
  pkg/acsengine/defaults.go
Labels: in progress, size/XS

#3183 wait 10 mins for k8s control plane
  parts/k8s/kubernetescustomscript.sh
Labels: in progress, orchestrator/k8s, size/XS

#3179 Kubernetes: explicitly install deps during provisioning
  parts/k8s/kubernetescustomscript.sh
Labels: in progress, orchestrator/k8s, size/XS

#3185 comment about hyperkube ubuntu deps in CSE
  parts/k8s/kubernetescustomscript.sh
Labels: in progress, size/XS

#3170 Gather metrics from openshift e2e tests
  test/e2e/openshift/util/util.go
  test/e2e/runner.go
Labels: approved, in progress, orchestrator/openshift, size/M

#3189 Prow updates
  .prowci/hook.yaml
  .prowci/plugins.yaml
  .prowci/tide.yaml
Labels: in progress, lgtm, size/XS

#2978 Add doc and sample for Openshift with custom vnet
  docs/openshift/deploy.md
  examples/vnet/openshift-vnet.json
  parts/k8s/kubernetesagentresourcesvmas.t
Labels: approved, in progress, lgtm, size/L

#3011 Use accelerated networking on agents
  docs/clusterdefinition.md
  examples/kubernetes-config/kubernetes-accelerated-network.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, do-not-merge/hold, in progress, lgtm, size/L

#3200 Add support for kubernetes 1.10.4
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3201 Add k8s 1.10 and 1.11 to master circleci build and remove swarm
  .circleci/config.yml
Labels: approved, in progress, lgtm, size/S

#3168 Fetch waagent logs for openshift e2e tests
  test/e2e/openshift/util/util.go
  test/e2e/runner.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/M

#3206 update error message
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
Labels: approved, in progress, lgtm, size/S

#3202 openshift: fix retry interval in rollout e2e test
  test/e2e/openshift/openshift_test.go
  test/e2e/openshift/util/util.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#3214 add Kubernetes 1.11.0-beta.2 support
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, orchestrator/k8s, size/XS

#3210 fix scale command on OpenShift
  cmd/scale.go
Labels: approved, in progress, lgtm, size/XS

#3218 DCOS: validate integrity of downloaded packages
  parts/dcos/bstrap/bootstrapcustomdata.yml
  parts/dcos/bstrap/bootstrapprovision.sh
  parts/dcos/bstrap/bootstrapresources.t
  parts/dcos/bstrap/dcosprovision.sh
  parts/dcos/dcosprovisionsource.sh
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/L

#3217 Vendor: move conform package out of testImport
  glide.lock
  glide.yaml
  vendor/github.com/influxdata/influxdb/stress/basic.go
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/LICENSE
  vendor/gopkg.in/yaml.v2/NOTICE
  vendor/gopkg.in/yaml.v2/README.md
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/decode_test.go
  vendor/gopkg.in/yaml.v2/emitterc.go
  vendor/gopkg.in/yaml.v2/encode.go
  vendor/gopkg.in/yaml.v2/encode_test.go
  vendor/gopkg.in/yaml.v2/example_embedded_test.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/readerc.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/sorter.go
  vendor/gopkg.in/yaml.v2/writerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: approved, in progress, lgtm, size/XXL

#3216 Adding notes on ACS-Engine v0.18.3 with Windows
  docs/kubernetes/windows.md
Labels: size/XS

#3199 Kubernetes: --image-pull-progress-deadline 30m by default
  docs/clusterdefinition.md
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
Labels: approved, in progress, orchestrator/k8s, size/XS

#3222 openshift: fix comment in ansible.sh
  .gitignore
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/master/tmp/ansible/ansible.sh
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/ansible.sh
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#3233 add etgryphon/stringUp dep
  glide.lock
  glide.yaml
  vendor/github.com/etgryphon/stringUp/.gitignore
  vendor/github.com/etgryphon/stringUp/README.md
  vendor/github.com/etgryphon/stringUp/stringUp.go
  vendor/github.com/etgryphon/stringUp/stringUp_test.go
Labels: approved, in progress, size/M

#3224 Update NVIDIA drivers to 396
  docs/kubernetes/gpu.md
  pkg/acsengine/engine.go
Labels: approved, in progress, lgtm, size/XS

#3230 Fix transient CSE exit 9
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/S

#3232 DCOS: added tags to VMs in cluster
  parts/dcos/bstrap/bootstrapresources.t
  parts/dcos/bstrap/dcosmasterresources.t
  parts/dcos/bstrap/dcosmastervars.t
  parts/dcos/dcosWindowsAgentResourcesVmas.t
  parts/dcos/dcosWindowsAgentResourcesVmss.t
  parts/dcos/dcosagentresourcesvmas.t
  parts/dcos/dcosagentresourcesvmss.t
  parts/dcos/dcosmastervars.t
Labels: approved, in progress, lgtm, size/M

#3131 OMS agent addon
  parts/k8s/addons/omsagent-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/acsengine/params_k8s.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/XL

#3093 Some refactoring of validation
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate_test.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/common/net.go
  pkg/api/common/net_test.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/XXL

#3209 add default reg dns
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/etc/origin/master/master-config.yaml
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#3193 Print the console URL upon successful cluster deploy.
  cmd/deploy.go
Labels: approved, in progress, lgtm, size/XS

#3188 Support --set flag in deploy command
  cmd/deploy.go
  cmd/deploy_test.go
  docs/kubernetes/deploy.md
Labels: in progress, kind/feature, size/L

#3250 Adding keyvaultSecretRef usage information to cluster definition docs
  docs/clusterdefinition.md
Labels: size/XS

#3252 Add apt-get update in apt-get install retry
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, lgtm, size/XS

#3243 Add cluster-autoscaler addon documentation
  docs/clusterdefinition.md
Labels: size/S

#3244 DCOS: use CDN to host Windows bootstrap binaries
  parts/dcos/dcosWindowsProvision.ps1
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/params.go
Labels: in progress, size/S

#3020 add default distro for agents.
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
Labels: approved, lgtm, orchestrator/openshift, size/M

#3162 Adding a validation when using existing vnet.
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, orchestrator/openshift, size/M

#3263 DCOS: added dns search to the cluster nodes
  parts/dcos/bstrap/bootstrapcustomdata.yml
Labels: approved, in progress, lgtm, size/S

#3248 quote base64 strings in the yaml files; use k8s compatible encoding for base64 values
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/vlabs/validate.go
Labels: size/S

#3198 Azure CNI networkmonitor addon
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/types.go
Labels: approved, in progress, size/XL

#3265 Variable fix for ansible-service-broker.
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-local-master-inventory.yml
Labels: approved, in progress, lgtm, size/XS

#3270 conditional AzureCNINetworkMonitorImageURL params
  pkg/acsengine/params_k8s.go
Labels: approved, in progress, kind/bug, lgtm, orchestrator/k8s, size/S

#3268 Adding validation for existing ip when using an existing vnet.
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/M

#3257 Update Calico to 3.1.3
  examples/networkpolicy/README.md
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
Labels: in progress, size/S

#2566 Configure kube-dns to expose metrics
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
Labels: approved, lgtm

#3207 Increase unit tests coverage in package api
  docs/clusterdefinition.md
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
Labels: approved, awaiting review, in progress, lgtm, size/XL

#3273 DCOS: disable VMSS overprovisioning
  parts/dcos/dcosWindowsAgentResourcesVmss.t
  parts/dcos/dcosagentresourcesvmss.t
Labels: approved, in progress, size/XS

#3275 Fix instance metadata + vmss default behavior for k8s 1.10.0 to 1.10.2
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, lgtm, size/S

#3278 don't exit CSE on apt.systemd.daily error
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3264 Set extension for custom DNS
  examples/vnet/kubernetesvnet-customnodesdns.json
  extensions/dnsupdate/v1/register-dns.sh
Labels: approved, lgtm, size/M

#3223 Support upgrading a Kubernetes cluster that contains Virtual Machine Scale Sets
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/compute.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, lgtm, size/L

#3274 Adding OpenShift e2e test for existing vnet.
  .circleci/config.yml
  examples/e2e-tests/openshift/definition.json
Labels: approved, in progress, lgtm, size/L

#3289 revert Azure CNI to 1.0.4
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3277 Updating the omsagent yaml file to include new changes for node zero dependency
  parts/k8s/addons/omsagent-daemonset.yaml
  pkg/acsengine/defaults.go
Labels: approved, size/L

#3242 Fixing panic issue in Validate when properties are nil
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/M

#3290 remove unnecessary nil check
  pkg/api/vlabs/validate.go
Labels: approved, in progress, size/XS

#3276 Refactor validateDNSPrefix function in one place
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/v20160330/validate.go
  pkg/api/v20160930/validate.go
  pkg/api/v20170131/validate.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, awaiting review, in progress, size/L

#3291 remove pathological test
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/XS

#3296 remove docker dependency from hyperkube extract
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, lgtm, size/L

#2910 Enable openshift e2e tests on centos
  .circleci/config.yml
Labels: approved, in progress, lgtm, orchestrator/openshift, size/M

#3286 Kubernetes: update to latest ubuntu 16.04 LTS image
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3285 Kubernetes: ensure params vals are bool, with test
  pkg/acsengine/params_k8s.go
  pkg/acsengine/params_k8s_test.go
  pkg/acsengine/testdata/addons/kubernetes.json
Labels: approved, in progress, lgtm, size/XL

#3294 fix(oms): pull oms directly from docker
  pkg/acsengine/defaults.go
Labels: in progress, size/XS

#3292 add annotation to secrets field
  pkg/api/agentPoolOnlyApi/v20170831/types.go
  pkg/api/agentPoolOnlyApi/v20180331/types.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#3304 run /usr/lib/apt/apt.systemd.daily in background
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3240 Kubernetes: Remove Windows-specific foo for control plane config
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-cloud-controller-manager.go
  pkg/acsengine/defaults-controller-manager.go
  pkg/acsengine/defaults-scheduler.go
  pkg/acsengine/defaults-scheduler_test.go
Labels: approved, backlog, in progress, kind/bug, lgtm, size/L

#3308 Remove duplicate ebtables apt-get install arg
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, orchestrator/k8s, size/XS

#3298 Adding tests to ensure plugins for container monitoring are running fine.
  parts/k8s/addons/omsagent-daemonset.yaml
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, lgtm, size/M

#3300 More unit tests
  pkg/acsengine/ssh_test.go
  pkg/helpers/helpers_test.go
Labels: approved, in progress, lgtm, size/L

#3314 Fail faster if no outbound internet
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3315 fix missing exit keyword in cse
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3316 Remove dependency on ci in codecov yaml
  .codecov/codecov.yml
Labels: approved, do-not-merge/hold, in progress, lgtm, size/XS

#3318 Kubernetes: get img from acs-mirror
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, orchestrator/k8s, size/XS

#3322 Fix ssh to get logs in e2e tests
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, lgtm, size/S

#3310 Move openshift infra resources into separate template file
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/openshift/infraresources.t
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
Labels: approved, in progress, lgtm, size/L

#3312 attempt to deal with waagent and docker racing
  parts/openshift/release-3.9/openshiftmasterscript.sh
  parts/openshift/release-3.9/openshiftnodescript.sh
  parts/openshift/unstable/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftnodescript.sh
Labels: approved, in progress, lgtm, size/M

#3328 openshift: workaround other bad images with an additional umount
  parts/openshift/unstable/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftnodescript.sh
Labels: approved, in progress, lgtm, size/XS

#3327 support for Kubernetes v1.10.5 and v1.11.0-rc.1
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, orchestrator/k8s, size/XS

#3330 Reduce docker pull timeout for hyperkube image
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3329 Update the URL for the Kubernetes Example
  docs/kubernetes.md
Labels: approved, lgtm, size/XS

#3320 Update Cluster Autoscaler to v1.3
  docs/clusterdefinition.md
  examples/addons/cluster-autoscaler/README.md
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
Labels: approved, in progress, lgtm, size/XL

#3336 updating the agent image to use the latest version for testing
  pkg/acsengine/defaults.go
Labels: approved, lgtm, size/XS

#3226 Use oreg_url from file if present
  parts/openshift/release-3.9/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftmasterscript.sh
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/release39/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-local-master-inventory.yml
Labels: approved, in progress, lgtm, orchestrator/openshift, size/S

#3332 Enabling 2 Windows E2E tests
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/util/util.go
Labels: approved, in progress, lgtm, size/L, windows

#3340 undo cilium changes to base64 encoding
  examples/networkpolicy/kubernetes-cilium.json
  parts/k8s/kubernetesmastercustomdata.yml
Labels: approved, in progress, size/XS

#3348 moving journald restart to end of config function
  parts/k8s/kubernetescustomscript.sh
Labels: approved, lgtm, size/XS

#3345 Kubernetes: update to latest version of CNI plugin
  pkg/acsengine/defaults.go
Labels: approved, in progress, orchestrator/k8s, size/XS

#2973 Remove docker
  examples/e2e-tests/kubernetes/kubernetes-config/containerd.json
  examples/e2e-tests/kubernetes/kubernetes-config/flannel.json
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#3353 Doc update: fix example kubernetes-vmas.json link
  docs/kubernetes/features.md
Labels: approved, lgtm, size/XS

#3351 Added more unit tests
  pkg/api/agentPoolOnlyApi/vlabs/types_test.go
  pkg/api/common/versions_test.go
  pkg/api/v20160330/types_test.go
  pkg/api/v20160930/types.go
  pkg/api/v20160930/types_test.go
  pkg/api/v20170131/types_test.go
  pkg/api/v20170701/types_test.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/armhelpers/deploymentError_test.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/helpers/helpers_test.go
Labels: approved, size/XL

#3356 fix(addons): Adds missing cluster subnet substitution for flannel
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
Labels: size/XS

#3357 Add support for Kubernetes v1.11.0-rc.2
  .circleci/config.yml
  pkg/api/common/versions.go
Labels: approved, in progress, size/M

#3359 fix nil panic in cluster autoscaler validation
  docs/clusterdefinition.md
  pkg/api/vlabs/validate.go
Labels: approved, awaiting review, in progress, lgtm, size/XS

#3346 add a basic DNS livenessprobe test
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/dns-liveness.yaml
Labels: approved, lgtm, orchestrator/k8s, size/M

#3301 Fix for kubelet startup script when using azure cni
  parts/k8s/kuberneteswindowssetup.ps1
Labels: approved, size/S

#3361 Kubernetes: Ubuntu 16.04.201806220
  pkg/acsengine/defaults.go
Labels: approved, in progress, size/XS

#3365 Kubernetes E2E: test for DNS failures before calico
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/M

#3370 E2E: don’t run dns livenessprobe test w/ calico
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, orchestrator/k8s, size/S

#3363 openshift: add SecurityGroupName and PrimaryAvailabilitySetName to azure.conf
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/openshift/certgen/release39/config.go
  pkg/openshift/certgen/release39/defaults.go
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/node/etc/azure/azure.conf
  pkg/openshift/certgen/unstable/config.go
  pkg/openshift/certgen/unstable/defaults.go
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/node/etc/origin/cloudprovider/azure.conf
Labels: approved, in progress, lgtm, size/L, ¯\_(ツ)_/¯

#3372 Kubernetes: update etcd to 3.2.23
  pkg/acsengine/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/XS

#3360 vmss Microsoft.AKS billing extension
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, in progress, size/S

#3367 Adds the missing logic for handling the preProvision extensions on Wi…
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/template_generator.go
Labels: approved, lgtm, size/XS

#3376 add Kubernetes v1.11.0-rc.3 support
  pkg/api/common/versions.go
Labels: approved, orchestrator/k8s, size/XS

#3354 Fetch openshift test image from new location
  .circleci/config.yml
Labels: approved, in progress, lgtm, orchestrator/openshift, size/XS

#3181 add GPU ExtendedResourceToleration admission controller support
  parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesbase.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
Labels: approved, lgtm, size/L

#3379 Kubernetes v1.11.0
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3205 Add Azure-npm to provide native k8s network policy support
  docs/clusterdefinition.md
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/api/const.go
  pkg/api/convertertoapi.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, awaiting review, lgtm, size/L

#3374 rev component versions for Kubernetes 1.11
  pkg/acsengine/k8s_versions.go
Labels: do-not-merge/work-in-progress, size/XS
