Repository Azure/acs-engine, pull requests merged in 2018-09, with the labels that each got.

#3790 E2E: enable "skip collect logs after test"
  test/e2e/config/config.go
  test/e2e/runner.go
Labels: approved, in progress, lgtm, size/XS

#3756 Make cmd more testable by abstracting authArgs and AzureClient
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/root.go
Labels: approved, in progress, lgtm, size/L

#3793 Remove etcd binary in agent VMs
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/XS

#3797 Remove non-existing priority class from Azure Network Policy Manager
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
Labels: approved, in progress, size/XS

#3801 Fix GPU driver install VHD
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, lgtm, size/M

#3800 Fixing #3791 - Windows nodes not working with kubenet plugin
  parts/k8s/kuberneteswindowssetup.ps1
Labels: approved, in progress, lgtm, size/S

#3804 store Azure CNI version in api model
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, size/M

#3805 Remove deprecated method calls in kubeclient
  pkg/armhelpers/kubeclient.go
Labels: approved, in progress, lgtm, size/S

#3808 adding ablitiy to login to an external tenant in azure client stuff
  pkg/armhelpers/azureclient.go
Labels: approved, in progress, lgtm, size/S

#3750 Reduce the Kubernetes version support matrix
  pkg/acsengine/testdata/agentPoolOnly/v20170831/agents.json
  pkg/acsengine/testdata/agentPoolOnly/v20180331/agents.json
  pkg/acsengine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfile.json
  pkg/acsengine/testdata/agentPoolOnly/v20180331/agentsWithFullNetworkProfileV2.json
  pkg/acsengine/testdata/agentPoolOnly/v20180331/agentsWithOnlyNetworkPlugin.json
  pkg/acsengine/testdata/v20170701/kubernetes-keyvault-secret.json
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/apiloader.go
  pkg/api/apiloader_test.go
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi_test.go
  pkg/api/orchestrators_test.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: approved, in progress, size/L

#3815 Simplifying condition check
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3818 Fix version deprecation validation for VMSS and windows clusters
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/M

#3809 Update AKS distro version
  pkg/acsengine/defaults.go
Labels: approved, in progress, size/XS

#3813 only enable aggregated api if rbac != disabled
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/helpers/helpers.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, lgtm, size/M

#3802 Enable "gosimple" linter plugin
  pkg/acsengine/defaults_test.go
  pkg/acsengine/tenantid_test.go
  pkg/acsengine/transform/apimodel_merger.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/types_test.go
  pkg/armhelpers/graph.go
  pkg/helpers/helpers_test.go
  scripts/validate-go.sh
  test/e2e/azure/cli.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, awaiting review, kind/chore, lgtm, size/L

#3794 Design doc
  docs/design/proposed-template-refactor.md
  docs/images/proposed-template-refactor.jpg
Labels: approved, area/docs, in progress, lgtm, size/L

#3814 E2E: reduce HPA thresholds
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/XS

#3817 Sync up health monitoring
  parts/k8s/health-monitor.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastercustomdata.yml
Labels: approved, in progress, size/M

#3819 Skip GPU driver install with golden image
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, lgtm, size/M

#3821 Change av profile default logic based on new version support matrix
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3823 add support for Kubernetes 1.11.3
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3825 add support for k8s v1.12.0-beta.1
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3826 AKS uses VHD + outbound inet test
  parts/k8s/kubernetescustomscript.sh
  pkg/acsengine/defaults.go
  pkg/api/const.go
Labels: approved, in progress, lgtm, size/S

#3829 user docker to pre-pull images during VHD CI
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/M

#3832 Removing code duplication in addon logic
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/L

#3763 Update to go 1.11 and fix new linting errors
  .circleci/config.yml
  Makefile
  cmd/deploy.go
  makedev.ps1
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/api/vlabs/validate_test.go
  pkg/helpers/helpers_test.go
  pkg/openshift/certgen/release39/kubeconfig.go
  pkg/openshift/certgen/release39/tls.go
  pkg/openshift/certgen/unstable/kubeconfig.go
  pkg/openshift/certgen/unstable/tls.go
  pkg/operations/kubernetesupgrade/upgrader.go
  test/e2e/openshift/openshift_test.go
Labels: approved, in progress, kind/chore, lgtm, size/L, test pipeline

#3838 Update go prerequisite to 1.11 and add links
  docs/developers.md
Labels: approved, area/docs, in progress, kind/documentation, lgtm, size/XS

#3836 update aks base image to 0.13.0
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3842 adding Tariq to the owners text file
  OWNERS
Labels: approved, in progress, lgtm, size/XS

#3844 Aesthetics: remove extra \n's in vhd metadata
  packer/install-dependencies.sh
Labels: approved, in progress, lgtm, size/XS

#3843 chore(deps): upgrade go-autorest to v10.15.4
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/Azure/go-autorest/autorest/azure/async.go
  vendor/github.com/Azure/go-autorest/autorest/client.go
  vendor/github.com/Azure/go-autorest/logger/logger.go
  vendor/github.com/Azure/go-autorest/version/version.go
Labels: approved, kind/chore, lgtm, size/L

#3841 update keyvault-flexvol image and default to enabled
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  pkg/api/const.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/M

#3840 Adding rawData script input for k8s addons
  docs/clusterdefinition.md
  pkg/acsengine/artifacts.go
  pkg/acsengine/const.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/testdata/addons/kubernetes-kube-proxy.json
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, size/XL

#3849 Reduce k8s versons in VHD image
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
Labels: approved, in progress, lgtm, size/XS

#3862 add retry to nvidia drivers install
  parts/k8s/kubernetesconfigs.sh
Labels: approved, in progress, lgtm, size/XS

#3863 Fixing tear-inducing typos
  parts/swarm/swarmmastervars.t
  pkg/acsengine/engine.go
Labels: approved, in progress, lgtm, size/XS

#3857 Update AKS base image to 0.14.0
  pkg/acsengine/defaults.go
  pkg/api/const.go
Labels: approved, in progress, lgtm, size/XS

#3855 Update cluster role bindings for azure-cloud-provider
  parts/k8s/addons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
Labels: approved, in progress, size/M

#3845 Fix scale with MSI
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
Labels: approved, in progress, kind/bug, lgtm, size/M

#3868 add support for Kubernetes 1.10.8
  packer/install-dependencies.sh
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3861 add function CreateContainer and SaveBlockBlob
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/storage.go
  pkg/armhelpers/storage_test.go
  pkg/operations/deletevm.go
Labels: approved, in progress, lgtm, size/L

#3777 Add acs-engine deploy e2e test
  test/e2e/config/config.go
  test/e2e/engine/cli.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, area/ci, in progress, lgtm, size/L

#3872 add support for k8s v1.12.0-rc.1
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3869 Adding DeleteApp func to AzureClient and returning appObjectID in CreateApp
  cmd/deploy.go
  pkg/armhelpers/graph.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/helpers/helpers.go
Labels: approved, in progress, lgtm, size/M

#3870 Update AKS base image to 0.15.0
  pkg/acsengine/defaults.go
Labels: approved, in progress, kind/chore, lgtm, orchestrator/k8s, size/XS

#3874 Disable AKS VHD for sovereign clouds
  docs/clusterdefinition.md
  pkg/acsengine/defaults.go
Labels: approved, in progress, kind/bug, lgtm, size/M

#3878 disable outbound internet check
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3871 Optimizing template conditional blocks in K8s templates
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
Labels: approved, in progress, size/L

#3854 Enforce windows password complexity requirements in acs-engine client…
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/M

#3881 Replace deprecated Azure SDK method calls
  pkg/armhelpers/compute.go
  pkg/armhelpers/deployments.go
  pkg/armhelpers/disk.go
  pkg/armhelpers/groupsclient.go
  pkg/armhelpers/network.go
Labels: approved, in progress, lgtm, size/S

#3879 Adding test case for Generate Cluster ID
  pkg/acsengine/engine_test.go
Labels: approved, in progress, lgtm, size/S

#3864 Add availability zone support for masters
  docs/clusterdefinition.md
  examples/e2e-tests/kubernetes/zones/definition.json
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  parts/masterparams.t
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/params.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/XL

#3886 Update docs for AZ
  docs/clusterdefinition.md
  examples/kubernetes-zones/README.md
Labels: approved, area/docs, in progress, lgtm, size/M

#3885 E2E - enable focused tests
  test/e2e/config/config.go
  test/e2e/runner.go
  test/e2e/runner/ginkgo.go
Labels: approved, in progress, lgtm, size/S

#3892 Re-enable outbound internet check
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, size/XS

#3895 Create moby branch for VHD CI
  docs/clusterdefinition.md
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesparams.t
  parts/k8s/kubernetesprovisionsource.sh
  parts/k8s/setup-custom-search-domains.sh
  pkg/acsengine/template_generator.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, size/L

#3893 add support for k8s v1.12.0-rc.2
  pkg/api/common/versions.go
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3894 Handle iterated subtest execution correctly
  pkg/api/agentPoolOnlyApi/v20180331/validate_test.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/S

#3891 Actually allow cloudprovider rate limit / backoff disabling
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/k8s_versions.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/L

#3877 Extracting property values to make ARM output variables accessible
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/output.go
  pkg/acsengine/output_test.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/XL

#3901 Fixing unreported gosimple lints
  pkg/api/vlabs/validate.go
  pkg/armhelpers/graph.go
Labels: approved, in progress, lgtm, size/XS

#3904 Add shortcuts for some common command-line arguments
  cmd/deploy.go
  cmd/generate.go
  cmd/root.go
  cmd/scale.go
  cmd/upgrade.go
Labels: approved, in progress, lgtm, size/S

#3912 Add zip package to VHD image
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, kind/chore, lgtm, size/XS

#3913 Update AKS base image to 0.16.0
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3919 Allow service principals with double-quote (") and backslash (\)
  parts/k8s/kubernetesconfigs.sh
Labels: approved, in progress, lgtm, size/XS
