Repository Azure/acs-engine, pull requests merged in 2018-05, with the labels that each got.

#2817 don’t delete cluster if failed deployment
  test/e2e/config/config.go
  test/e2e/runner.go
Labels: in progress

#2821 Update docker image for kms service
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: in progress

#2792 deploy OpenShift registry-console with openshift-ansible
  parts/openshift/openshiftmasterscript.sh
  pkg/openshift/certgen/templates/bindata.go
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/templates/master/tmp/ansible/azure-ocp-deploy.yml
Labels: orchestrator/openshift

#2781 Added check to ensure initial NSG is not for jumpbox
  pkg/acsengine/transform/transform.go
Labels: cse-sync-week, in progress

#2814 add k8s 1.11 e2e
  .circleci/config.yml
  docs/clusterdefinition.md
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/api/common/versions.go
Labels: in progress

#2780 Cleanup openshift file permissions and ownership.
  parts/openshift/openshiftmasterscript.sh
  pkg/openshift/certgen/config_test.go
  pkg/openshift/certgen/files.go
  pkg/openshift/certgen/kubeconfig.go
  pkg/openshift/certgen/tls.go
  pkg/openshift/filesystem/filesystem.go
Labels: orchestrator/openshift

#2825 Deploying DCOS clusters using bootstrap node (starting v1.11)
  parts/dcos/bstrap/bootstrapcustomdata.yml
  parts/dcos/bstrap/bootstrapparams.t
  parts/dcos/bstrap/bootstrapprovision.sh
  parts/dcos/bstrap/bootstrapresources.t
  parts/dcos/bstrap/bootstrapvars.t
  parts/dcos/bstrap/dcosbase.t
  parts/dcos/bstrap/dcoscustomdata111.t
  parts/dcos/bstrap/dcosmasterresources.t
  parts/dcos/bstrap/dcosmastervars.t
  parts/dcos/bstrap/dcosprovision.sh
  parts/dcos/dcosagentresourcesvmas.t
  parts/dcos/dcosagentresourcesvmss.t
  parts/dcos/dcoscustomdata111.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/testdata/vnet/dcosvnet.json
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: in progress

#2803 Add Kubernetes v1.8.12 support
  pkg/api/common/versions.go
Labels: in progress

#2804 Documentation about how to run Kubernetes in an hybrid env
  docs/README.md
  docs/images/kubernetes-hybrid-env.png
  docs/kubernetes/hybrid-environment.md
Labels: awaiting review, kind/documentation

#2820 Fix deploy using client-id and client-secret
  cmd/deploy.go
  cmd/deploy_test.go
Labels: in progress

#2841 infer e2e cleanup from global circle config
  .circleci/config.yml
Labels: in progress

#2840 make dcos-diagnostics-runner-config fix package independent
  parts/dcos/bstrap/dcoscustomdata111.t
Labels: in progress

#2771 acs-engine deploy: model validation and required fields in --help
  cmd/deploy.go
  cmd/root.go
Labels: cse-sync-week, ready

#2843 kms using deprecated systemd convenience
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#2786 Add the new signing key for the azure cli package
  Dockerfile
Labels: in progress

#2813 rationalize network config and k8s NetworkPolicy
  docs/clusterdefinition.md
  docs/kubernetes/features.md
  examples/azure-cni/k8s-scaledown.json
  examples/azure-cni/k8s-scaleup.json
  examples/azure-cni/k8s-vnet-scaledown.json
  examples/azure-cni/k8s-vnet-scaleup.json
  examples/coreos/kubernetes-coreos-hybrid.json
  examples/coreos/kubernetes-coreos.json
  examples/e2e-tests/kubernetes/kubernetes-config/clear-containers.json
  examples/e2e-tests/kubernetes/kubernetes-config/network-plugin-kubenet.json
  examples/kubernetes-clear-containers.json
  examples/networkplugin/README.md
  examples/networkplugin/kubernetes-azure.json
  examples/networkpolicy/README.md
  examples/vnet/kubernetesvnet.json
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/api/agentPoolOnlyApi/v20180331/apiloader_test.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/convertertoagentpoolonlyapi_test.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
  pkg/api/types.go
  pkg/api/vlabs/const.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2787 Create a --set flag for generate
  cmd/generate.go
  cmd/generate_test.go
  docs/kubernetes/deploy.md
  glide.lock
  glide.yaml
  pkg/acsengine/transform/apimodel_merger.go
  pkg/acsengine/transform/apimodel_merger_test.go
  vendor/github.com/Jeffail/gabs/LICENSE
  vendor/github.com/Jeffail/gabs/README.md
  vendor/github.com/Jeffail/gabs/gabs.go
  vendor/github.com/Jeffail/gabs/gabs_logo.png
  vendor/github.com/Jeffail/gabs/gabs_test.go
Labels: awaiting review, cse-sync-week, in progress

#2849 bumped to 1.1.0 release of containerd-cri
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#2853 setting mesos attributes for agent nodes
  parts/dcos/bstrap/dcoscustomdata111.t
  pkg/acsengine/engine.go
Labels: in progress

#2854 apply back-compat networkPolicy to unversioned api
  pkg/api/const.go
  pkg/api/convertertoapi.go
  pkg/api/convertertoapi_test.go
Labels: in progress

#2856 Reword cmd descriptions
  cmd/deploy.go
  cmd/orchestrators.go
  cmd/scale.go
  cmd/upgrade.go
  docs/acsengine.md
  docs/acsengine.zh-CN.md
Labels: in progress

#2822 Set Windows Azure CNI config
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/defaults.go
Labels: DO-NOT-MERGE, in progress

#2864 simplified DCOS bootstrap deployment
  parts/dcos/bstrap/bootstrapcustomdata.yml
  parts/dcos/bstrap/bootstrapprovision.sh
Labels: in progress

#2635 flannel: add support
  examples/kubernetes-clear-containers.json
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_template.json
  pkg/api/vlabs/const.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: in progress

#2865 change the docker service sequence
  parts/dcos/bstrap/dcoscustomdata111.t
Labels: in progress

#2867 cmd package refactor and unit tests
  cmd/deploy.go
  cmd/root.go
  cmd/scale.go
  cmd/upgrade.go
  cmd/upgrade_test.go
  cmd/version.go
  cmd/version_test.go
Labels: in progress

#2866 update ubuntu image to 16.04.201804270
  pkg/acsengine/defaults.go
Labels: in progress

#2879 Fix broken upgrade nil pointer dereference
  cmd/upgrade.go
Labels: in progress

#2878 k8s cloud-init more retries, some rationalization
  parts/k8s/kubernetes_mountetcd.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/acsengine/engine.go
Labels: DO-NOT-MERGE, in progress, orchestrator/k8s

#2875 refactor build script and download wincni from github
  scripts/build-windows-k8s.sh
  windows/Hns.psm1
Labels: in progress

#2898 use CDN for bootstrap provisioning
  parts/dcos/bstrap/bootstrapprovision.sh
Labels: in progress

#2637 Kubernetes Cluster Autoscaler (VMSS) addon
  examples/addons/cluster-autoscaler/README.md
  examples/addons/cluster-autoscaler/kubernetes-cluster-autoscaler.json
  parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: awaiting review

#2809 Remove default vnet and route table creation when using Azure CNI.
  parts/iaasoutputs.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/api/converterfromagentpoolonlyapi.go
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: in progress

#2839 First version of OpenShift docs
  README.md
  docs/openshift.md
  docs/openshift/OWNERS
  docs/openshift/deploy.md
Labels: orchestrator/openshift

#2914 require test before openshift e2e in master
  .circleci/config.yml
Labels: in progress

#2902 Update localization for strings
  scripts/update-enus-po.sh
  scripts/update-translation.sh
  translations/en_US/LC_MESSAGES/acsengine.po
  translations/en_US/LC_MESSAGES/acsengine.po.lcg
  translations/en_US/LC_MESSAGES/en-US/lcl/acsengine.po.lcl
  translations/en_US/LC_MESSAGES/en-US/metadata/acsengine.po.xml
Labels: in progress

#2915 use static default bool value for kubernetesClusterAutoscalerEnabled
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
Labels: in progress

#2920 dcos: simplified node provisioning, use CDN
  parts/dcos/bstrap/dcoscustomdata111.t
  parts/dcos/bstrap/dcosprovision.sh
Labels: in progress

#2945 Output empty virtualNetworkResourceGroupName in default kubenet case.
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#2939 updated URLs for Chinese cloud
  parts/dcos/bstrap/bootstrapprovision.sh
  parts/dcos/bstrap/dcosprovision.sh
Labels: in progress

#2921 E2E: DNS tests for kubernetes clusters
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/validate-dns.yaml
Labels: in progress, orchestrator/k8s, test pipeline

#2947 update kubernetes ubuntu image to 16.04.201805090
  pkg/acsengine/defaults.go
Labels: in progress, orchestrator/k8s

#2950 add unit tests for IsKubernetesVersionGe
  pkg/api/common/versions_test.go
Labels: in progress

#2940 ensure outputs section of template is empty json object on openshift scale
  pkg/acsengine/transform/transform.go
  pkg/acsengine/transform/transform_test.go
Labels: orchestrator/openshift

#2707 feat(ext): Add choco extension with param support
  extensions/choco/README.md
  extensions/choco/v1/ChocolateyPackageInstaller.ps1
  extensions/choco/v1/startChocolatey.ps1
  extensions/choco/v1/supported-orchestrators.json
  extensions/choco/v1/template-link.json
  extensions/choco/v1/template.json
Labels: awaiting review

#2959 Add unit tests for v2018-03-31 AADProfile
  pkg/api/converterfromagentpoolonlyapi_test.go
  pkg/api/convertertoagentpoolonlyapi_test.go
Labels: in progress

#2964 Enabling DCOS 1.11.2
  parts/dcos/bstrap/dcos1.11.0.customdata.t
  parts/dcos/bstrap/dcos1.11.2.customdata.t
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/api/common/const.go
  pkg/api/const.go
  pkg/api/convertertoapi.go
Labels: in progress

#2968 use isKubernetesVersionGe go func in template
  pkg/acsengine/engine.go
Labels: in progress

#2955 Fix Windows sku + offer + publisher k8s and swarm variables
  parts/k8s/kubernetesmastervars.t
  parts/swarm/swarmmastervars.t
Labels: in progress

#2983 LEGO: Pull request from lego/hb_946_20180516115347175 to master
  loc/cs-CZ/acsengine.po.lcl
  loc/de-DE/acsengine.po.lcl
  loc/es-ES/acsengine.po.lcl
  loc/fr-FR/acsengine.po.lcl
  loc/hu-HU/acsengine.po.lcl
  loc/it-IT/acsengine.po.lcl
  loc/ja-JP/acsengine.po.lcl
  loc/ko-KR/acsengine.po.lcl
  loc/nl-NL/acsengine.po.lcl
  loc/pl-PL/acsengine.po.lcl
  loc/pt-BR/acsengine.po.lcl
  loc/pt-PT/acsengine.po.lcl
  loc/ru-RU/acsengine.po.lcl
  loc/sv-SE/acsengine.po.lcl
  loc/tr-TR/acsengine.po.lcl
  loc/zh-CN/acsengine.po.lcl
  loc/zh-TW/acsengine.po.lcl
Labels: in progress

#2979 Add retry in dowloading windows zip
  parts/k8s/kuberneteswindowssetup.ps1
Labels: in progress

#2881 k8s provision only in CSE
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/engine.go
Labels: in progress

#2987 do not use public IP for bootstrap node
  parts/dcos/bstrap/bootstrapparams.t
  parts/dcos/bstrap/bootstrapresources.t
  parts/dcos/bstrap/bootstrapvars.t
  parts/dcos/bstrap/dcosmasterresources.t
  parts/dcos/dcosagentresourcesvmas.t
  parts/dcos/dcosagentresourcesvmss.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/testdata/vnet/dcosvnet.json
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: in progress

#2988 Allow Windows and Linux to have different default k8s versions
  pkg/api/common/const.go
  pkg/api/common/versions.go
Labels: in progress

#2975 add Kubernetes v1.8.13 support
  pkg/api/common/versions.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2798 Validation for WindowsProfile
  pkg/api/vlabs/validate.go
Labels: cse-sync-week, in progress

#3000 Remove usages of outdated uuid libraries.
  pkg/acsengine/defaults-apiserver_test.go
  pkg/api/vlabs/validate.go
Labels: approved, lgtm

#3004 wait the full timeout for pod DNS
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/XS

#2994 removing the vnet from scale templates
  pkg/acsengine/transform/transform.go
  pkg/acsengine/transform/transformtestfiles/TestNormalizeForK8sVMASScalingUpWithVnet.failure.json
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
Labels: approved, lgtm, ready

#3003 Add support for building win zip from for e2e testing
  scripts/build-windows-k8s.sh
Labels: approved, lgtm, size/L

#2995 Adding example on how to switch Windows versions and OS disk size
  docs/kubernetes/windows.md
Labels: approved, size/M

#2992 Update docs for Azure CNI subnet requirements
  docs/kubernetes/features.md
  examples/kubernetes-config/kubernetes-private-cluster-single-master.json
  examples/kubernetes-config/kubernetes-private-cluster.json
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/S

#3014 Update cluster-autoscaler addon to v1.2.2
  pkg/acsengine/k8s_versions.go
Labels: approved, in progress, lgtm, size/XS

#2925 Configure heapster for RBAC from K8S 1.9 and above
  parts/k8s/addons/kubernetesmasteraddons-heapster-deployment.yaml
Labels: approved, lgtm

#2901 update azureconst
  pkg/acsengine/Get-AzureConstants.py
  pkg/acsengine/azureconst.go
Labels: approved, in progress

#3007 Fixing redundant err != nil checks
  pkg/api/agentPoolOnlyApi/v20170831/validate.go
  pkg/api/agentPoolOnlyApi/v20180331/validate.go
  pkg/api/agentPoolOnlyApi/vlabs/validate.go
  pkg/api/v20160330/validate.go
  pkg/api/v20160930/validate.go
  pkg/api/v20170131/validate.go
  pkg/api/v20170701/validate.go
  pkg/api/vlabs/validate.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, size/M

#3019 Fixed dead links in documentation.
  docs/swarm.md
  docs/swarmmode-hybrid.md
  docs/swarmmode.md
Labels: approved, area/docs, size/M

#3018 Fix prometheus extension due to renaming cse
  extensions/prometheus-grafana-k8s/v1/prometheus-grafana-k8s.sh
  extensions/prometheus-grafana-k8s/v1/template-link.json
  extensions/prometheus-grafana-k8s/v1/template.json
  pkg/acsengine/engine.go
Labels: in progress, size/S

#3030 DCOS: implement upgrade operation for clusters with bootstrap node
  cmd/dcos-upgrade.go
  cmd/dcos-upgrade_test.go
  cmd/root.go
  docs/dcos.md
  pkg/api/orchestrators.go
  pkg/operations/dcosupgrade/upgradecluster.go
  pkg/operations/dcosupgrade/upgrader.go
  pkg/operations/remote_ssh.go
Labels: approved, in progress, lgtm, size/XL

#2980 Support for Low-priority VMs on Virtual Machine Scale Sets (VMSS) for Kubernetes
  docs/clusterdefinition.md
  examples/kubernetes-vmss-low-priority/kubernetes.json
  parts/agentparams.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesagentvars.t
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
Labels: lgtm, size/L

#3028 add support for Kubernetes v1.10.3
  pkg/api/common/versions.go
Labels: in progress, orchestrator/k8s, size/XS

#3041 cleanup openshift e2e, retain if fail for k8s
  .circleci/config.yml
Labels: area/ci, size/XS

#3031 Fix extensions not working
  extensions/choco/v1/template-link.json
  extensions/choco/v1/template.json
  extensions/hello-world-k8s/v1/template-link.json
  extensions/hello-world-k8s/v1/template.json
  extensions/microsoft-oms-agent-k8s/v1/template-link.json
  extensions/microsoft-oms-agent-k8s/v1/template.json
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/acsengine/engine.go
  pkg/acsengine/testdata/extensions/swarmmode.json
  pkg/api/vlabs/validate.go
Labels: approved, ready, size/M

#2972 Adding necessary configuration for 3.10 Openshift nodes.
  parts/openshift/unstable/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftnodescript.sh
  pkg/acsengine/engine.go
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-ocp-deploy.yml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/openshift/certgen/unstable/templates/node/etc/origin/cloudprovider/azure.conf
  pkg/openshift/certgen/unstable/templates/node/etc/origin/node/node-dnsmasq.conf
Labels: size/L

#2769 update openshift validations to match patterns
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, orchestrator/openshift

#2923 Setup prow CI
  .prowci/.gitignore
  .prowci/Makefile
  .prowci/README.md
  .prowci/config.yaml
  .prowci/deck.yaml
  .prowci/hook.yaml
  .prowci/ingress.yaml
  .prowci/plugins.yaml
  .prowci/tide.yaml
Labels: approved, size/L

#3059 Revert vmss extension name
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
Labels: approved, in progress, lgtm, size/XS

#2934 Delete role assignments when deleting a VM
  .gitignore
  cmd/scale.go
  pkg/armhelpers/graph.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/operations/deletevm.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
  pkg/operations/kubernetesupgrade/upgrademasternode.go
  pkg/operations/kubernetesupgrade/upgrader.go
  pkg/operations/scaledownagentpool.go
  pkg/operations/scaledownagentpool_test.go
Labels: DO-NOT-MERGE, approved, lgtm, size/L

#2903 Autofill ACI Connector credentials and enable logs
  examples/addons/aci-connector/README.md
  examples/addons/aci-connector/kubernetes-aci-connector.json
  parts/k8s/addons/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
Labels: approved, in progress, lgtm, size/L

#3066 DCOS: added DC/OS post-installation step
  parts/dcos/bstrap/dcos1.11.0.customdata.t
  parts/dcos/bstrap/dcos1.11.2.customdata.t
Labels: approved, in progress, lgtm, size/S

#3077 SP with resource group level scope example
  docs/serviceprincipal.md
Labels: area/docs, size/S

#2996 openshift: record etcd logs in test runs
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
Labels: approved, orchestrator/openshift, size/M

#3050 update docs
  docs/clusterdefinition.md
  docs/developers.md
  docs/extensions.md
Labels: approved, orchestrator/openshift, size/M

#3073 remove go get for bindata and rely on Makefile bootstrap target used …
  pkg/openshift/certgen/release39/templates/templates.go
  pkg/openshift/certgen/unstable/templates/templates.go
Labels: approved, lgtm, orchestrator/openshift, size/XS

#3045 Adding Windows troubleshooting section
  docs/kubernetes/windows.md
Labels: approved, area/docs, size/L

#3096 Create kubernetes1.10.json
  examples/kubernetes-releases/kubernetes1.10.json
Labels: size/M

#3005 Kubernetes CSE retries
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: DO-NOT-MERGE, approved, in progress, orchestrator/k8s, size/M

#3065 Rationalize AvailabilityProfile default
  docs/clusterdefinition.md
  examples/kubernetes.json
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, lgtm, ready, size/M

#3104 Set Azure CNI default mode to l2bridge
  parts/k8s/kuberneteswindowssetup.ps1
Labels: approved, size/XS

#3103 Add CSE VM extension error troubleshooting guide
  docs/kubernetes/troubleshooting.md
Labels: approved, awaiting review, in progress, lgtm, size/M

#3106 Use collaborators again now that we have an openshift team
  .prowci/plugins.yaml
Labels: approved, in progress, lgtm, size/XS

#3092 increased VM size for e2e dcos deployments
  examples/dcos-releases/dcos1.10.json
  examples/dcos-releases/dcos1.8.json
  examples/dcos-releases/dcos1.9.json
  examples/dcos.json
  examples/disks-managed/dcos-preAttachedDisks-vmas.json
  examples/disks-managed/dcos-vmss.json
  examples/disks-storageaccount/dcos.json
  examples/vnet/dcosvnet.json
  test/cluster-tests/dcos/test.sh
  test/e2e/dcos-deployments.json
  test/e2e/dcos/dcos.go
Labels: approved, in progress, lgtm, size/M

#3048 Custom images e2e
  test/e2e/engine/template.go
Labels: approved, lgtm, size/S

#2986 ensure openshift examples stay in sync for base attributes
  pkg/openshift/examples_test.go
Labels: approved, lgtm, orchestrator/openshift

#2736 Add pod-pid-limit options to kubelet in kubernetes 1.10
  docs/clusterdefinition.md
  pkg/acsengine/const.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults_test.go
Labels: approved, lgtm

#3090 Use enable-admission-plugins key for v1.10 and above
  docs/clusterdefinition.md
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
Labels: approved, in progress, lgtm, size/M

#3108 ensure --admission-control is removed for 1.10
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
Labels: in progress, kind/bug, size/S

#2545 NVIDIA Device Plugin
  docs/kubernetes/gpu.md
  examples/addons/nvidia-device-plugin/README.md
  examples/addons/nvidia-device-plugin/nvidia-device-plugin.json
  parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/types.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/cuda-vector-add.yaml
Labels: approved, in progress, lgtm, size/XL

#2590 Custom Search Domains
  docs/clusterdefinition.md
  examples/vnet/kubernetesvnet-customsearchdomain.json
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/setup-custom-search-domains.sh
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#3120 DCOS: Windows custom script extension to pass exit code on
  parts/dcos/dcosWindowsProvision.ps1
  parts/dcos/dcosagentvars.t
Labels: approved, in progress, lgtm, size/XS

#3115 Add codecov yaml
  .codecov/codecov.yml
Labels: approved, in progress, lgtm, size/M

#3117 Fix k8s 1.11.0-alpha.2+ cluster bootstrap issue
  parts/k8s/artifacts/kuberneteskubelet.service
Labels: approved, lgtm, size/XS

#2838 add support for k8s 1.11.0-alpha.2
  pkg/api/common/versions.go
Labels: in progress, size/XS

#3112 remove pre-fill validation in deploy
  cmd/deploy.go
  cmd/deploy_test.go
Labels: approved, in progress, lgtm, size/XS

#3119 Updating the go-bindata go get paths
  Dockerfile.k8swin
  docs/acsengine.md
  pkg/acsengine/fileloader.go
  pkg/i18n/resourceloader.go
Labels: approved, lgtm, size/XS

#3129 Kubernetes: update ubuntu image to 16.04.201805220
  pkg/acsengine/defaults.go
Labels: in progress, orchestrator/k8s, size/XS

#3128 calico needs kubelet config —network-config=cni
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
Labels: in progress, orchestrator/k8s, size/S
