Repository Azure/acs-engine, pull requests merged in 2018-11, with the labels that each got.

#4116 Merging kubernetesmastervarsvmss into kubernetesmastervars
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomdatavmss.yml
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesmastervarsvmss.t
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/XL

#4159 virtualNetworkName is needed for vmss masters
  parts/k8s/kubernetesmastervars.t
Labels: approved, in progress, size/XS

#4162 vmss masters listen on firstConsecutiveStaticIP
  parts/k8s/kubernetesmastervars.t
Labels: in progress, size/XS

#4166 rationalize addons/kube-system e2e checks
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, e2e, in progress, lgtm, size/L

#4167 Ensure vmss masters with customvnet dependson master lb
  parts/k8s/kubernetesmasterresourcesvmss.t
Labels: approved, in progress, lgtm, size/XS

#4164 Remove unreachable NSG code
  parts/k8s/kubernetesbase.t
Labels: aks, approved, in progress, lgtm, size/M

#4156 move k8s specific params to params_k8s.go
  parts/k8s/kubernetesbase.t
  parts/windowsparams.t
  pkg/acsengine/params.go
  pkg/acsengine/params_k8s.go
Labels: approved, in progress, lgtm, size/M

#4180 remove obsolete kubernetesmastervarsvmss.t
  parts/k8s/kubernetesmastervarsvmss.t
Labels: approved, in progress, lgtm, size/XS

#4181 add Skip functionality for skipped E2E tests
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/S

#4174 Pre-pull hyperkube in VHD
  packer/install-dependencies.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/M

#4190 use gcr.azk8s.cn for all add-on configs on Azure China
  parts/k8s/kubernetesmastercustomdata.yml
Labels: approved, lgtm, size/XS

#4195 Call cleanUpContainerImages in CSE
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, size/XS

#4194 add AKS container images to VHD build script
  packer/install-dependencies.sh
Labels: aks, approved, in progress, size/S

#4193 Update ip assignment and cert gen for vmss masters
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/api/defaults-openshift-certs.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: approved, in progress, lgtm, size/L

#4197 Azure CNI v1.0.13
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: approved, lgtm, size/XS

#3968 Enable upgrade to next supported Kubernetes version
  pkg/api/common/versions.go
  pkg/api/common/versions_test.go
  pkg/api/orchestrators.go
  pkg/api/orchestrators_test.go
  pkg/armhelpers/mockclients.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: aks, approved, in progress, lgtm, size/L

#4199 More validations for custom vnet and vmss masters
  docs/kubernetes/features.md
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, in progress, lgtm, size/M

#4202 fix cilium cluster config
  parts/k8s/addons/kubernetesmasteraddons-cilium-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/M

#4154 Calico support for azure-vnet-ipam
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  pkg/api/defaults.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: aks, approved, in progress, lgtm, size/L

#4201 Update VHD image to 2018.11.06
  parts/k8s/kubernetesinstalls.sh
  pkg/api/azenvtypes.go
Labels: approved, do-not-merge/hold, in progress, lgtm, size/XS

#4203 move kubeserviceCidr params to windowsparams tpl
  parts/k8s/kubernetesparams.t
  parts/windowsparams.t
  pkg/acsengine/params_k8s.go
Labels: approved, in progress, size/S

#4204 Only cleanup AKS container images if cluster is not a hosted master cluster
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
Labels: approved, in progress, lgtm, size/S

#4205 2 units of CSE errata
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
Labels: approved, in progress, lgtm, size/XS

#4208 setting default Images in addon defaults instead of params_k8s.go
  pkg/acsengine/params_k8s.go
  pkg/api/addons.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
Labels: approved, in progress, size/L

#4210 mount xtables lock in proxy
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
Labels: lgtm, size/XS

#4211 test outbound for URLs that we know we need
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
Labels: approved, in progress, lgtm, size/XS

#4212 imagePullPolicy: IfNotPresent for all versioned containers
  docs/clusterdefinition.md
  packer/install-dependencies.sh
  parts/k8s/addons/1.10/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.6/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.6/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/addons/ip-masq-agent.yaml
  parts/k8s/addons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-heapster-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/addons/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/manifests/kubernetesmaster-cloud-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-addon-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  parts/k8s/manifests/kubernetesmaster-kube-controller-manager.yaml
  parts/k8s/manifests/kubernetesmaster-kube-scheduler.yaml
  pkg/api/defaults-apiserver.go
Labels: approved, in progress, size/M

#4217 Standard LB name must be a string
  parts/k8s/addons/kubernetesmasteraddons-elb-svc.yaml
Labels: approved, in progress, lgtm, size/XS

#4221 ensure N series clusters get aks-docker-engine
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/template_generator.go
  pkg/api/addons.go
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress, kind/bug

#4224 ensure addon image is overwritten during upgrade
  docs/clusterdefinition.md
  pkg/api/addons.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
Labels: in progress

#4223 Update to Docker 18.09 for Windows
  examples/windows/kubernetes-windows-docker-version.json
  parts/windowsparams.t
  pkg/api/const.go
Labels: in progress, windows

#4230 E2E: ensure validate-dns job doesn’t already exist before creating
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#4231 remove empty customdata yml file
  parts/k8s/kubernetesmastercustomdatavmss.yml
Labels: in progress

#4235 omsagent addon boilerplate fix
  parts/k8s/addons/kubernetesmasteraddons-omsagent-daemonset.yaml
Labels: in progress

#4237 E2E: azure npm addon has differently named pods
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#4232 E2E: ensure long-running-apache hpa doesn’t already exist before creating
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#4240 Adding c:\tmp as needed to pass Kubernetes tests
  parts/k8s/kuberneteswindowsfunctions.ps1
  parts/k8s/kuberneteswindowssetup.ps1
Labels: in progress

#4222 Add no outbound internet feature flag
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: in progress

#4247 update azure-const.sh with new location of azure constants python file
  scripts/azure-const.sh
Labels: in progress

#4244 Updating calico images to the latest release with security fixes
  parts/k8s/addons/1.10/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.11/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.7/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.8/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/1.9/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
Labels: in progress

#4218 Enable pre-rendering of Container addons
  parts/k8s/containeraddons/azure-cni-networkmonitor.yaml
  parts/k8s/containeraddons/dns-autoscaler.yaml
  parts/k8s/containeraddons/ip-masq-agent.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aad-pod-identity-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-aci-connector-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-blobfuse-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-kubernetes-dashboard-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-metrics-server-deployment.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-omsagent-daemonset.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-smb-flexvolume-installer.yaml
  parts/k8s/containeraddons/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/acsengine/artifacts.go
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/params_k8s_test.go
  pkg/acsengine/template_generator.go
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/types.go
Labels: in progress, size/L

#4142 Make orchestrator command Windows aware
  cmd/orchestrators.go
  pkg/api/orchestrators.go
Labels: approved, lgtm, size/S

#3907 Enable multiple Windows vmss agent pools - refactor pool names
  cmd/scale.go
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/armhelpers/utils/util.go
  pkg/armhelpers/utils/util_test.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, awaiting review, in progress, size/M, windows

#4233 consistent use of kubernetes image base
  docs/clusterdefinition.md
  pkg/acsengine/params_k8s.go
  pkg/acsengine/params_k8s_test.go
  pkg/acsengine/params_test.go
  pkg/api/defaults-kubelet.go
Labels: in progress

#4253 remove extraneous sed statements for mooncake
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#4252 Add exechealthz to 1.12/13 section as 1.11 or earlier
  pkg/api/k8s_versions.go
Labels: in progress

#4255 append bug means we aren’t cleaning up e2e for long-running clusters
  test/e2e/runner.go
Labels: in progress

#4258 *string PrincipalID needs to be nil-guarded
  pkg/operations/deletevm.go
Labels: in progress

#4263 fix retrycmd_if_failure: retries should be r
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
Labels: in progress

#4262 Add DockerEngine feature flag
  packer/feature-flagged.sh
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
Labels: in progress

#4265 updating azureconst and adding PB6 skus
  Makefile
  pkg/helpers/azureconst.go
Labels: in progress

#4266 use mcr repos and disable smb flexvol addon
  pkg/api/addons.go
  pkg/api/const.go
  pkg/api/defaults_test.go
  pkg/api/types_test.go
Labels: in progress

#4269 docker-health monitor doesn't work
  parts/k8s/health-monitor.sh
Labels: in progress

#4270 Replace docker engine feature flag by existing cloud spec
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/params_k8s.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
Labels: in progress

#4275 remove DockerEngine FeatureFlag
  pkg/api/types.go
Labels: in progress

#4273 E2E: rationalize node check + kube-system check, no kms
  .circleci/config.yml
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
  test/e2e/runner/cli_provisioner.go
Labels: in progress

#4276 install gpu drivers before extracting hyperkube
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#4268 [docs] Add documentation for GPU w/ docker-engine
  docs/clusterdefinition.md
  docs/kubernetes/gpu.md
  pkg/acsengine/params_k8s_test.go
Labels: area/docs, in progress

#4279 Fix issue caused by updating azure.json
  .circleci/config.yml
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: in progress

#4300 Set progresspreference to avoid progress bar and speed up downloads
  parts/k8s/kuberneteswindowsfunctions.ps1
Labels: in progress

#4297 Update to Azure-CNI v1.0.14
  packer/install-dependencies.sh
  pkg/api/const.go
Labels: in progress

#4302 Updates from aks-engine spike
  .circleci/config.yml
  .prowci/Makefile
  .prowci/README.md
  .prowci/config.yaml
  .prowci/hook.yaml
  .prowci/ingress.yaml
  .prowci/tide.yaml
  .vsts-ci.yaml
  Makefile
  cmd/scale.go
  makedev.ps1
  packer/install-dependencies.sh
  parts/k8s/containeraddons/ip-masq-agent.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesparams.t
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/api/addons.go
  pkg/api/common/versions.go
  pkg/api/const.go
  pkg/api/defaults.go
  pkg/api/defaults_test.go
  pkg/api/k8s_versions.go
  pkg/api/types.go
  pkg/helpers/Get-AzureConstants.py
  pkg/helpers/azureconst.go
  pkg/helpers/azureconst_test.go
  scripts/validate-generated.sh
  test/e2e/config/config.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/runner.go
  test/e2e/runner/cli_provisioner.go
  test/e2e/runner/ginkgo.go
Labels: in progress

#4304 Ensure all CSE outbound checks have retry tolerance
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmasterresourcesvmss.t
Labels: in progress

#4293 Adding doc on how to set Azure CNI versions
  docs/clusterdefinition.md
Labels: in progress

#4299 Support Windows Server 2019 and make it default
  docs/clusterdefinition.md
  docs/kubernetes/windows-details.md
  examples/windows/kubernetes-windows-version.json
  parts/k8s/windowskubeletfunc.ps1
  parts/windowsparams.t
  pkg/acsengine/params.go
  pkg/api/const.go
  pkg/api/types.go
  pkg/api/types_test.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: in progress

#4322 fix malformed clusterautoscaler yaml bug
  parts/k8s/containeraddons/kubernetesmasteraddons-cluster-autoscaler-deployment.yaml
  pkg/api/addons.go
Labels: in progress

#4315 update kubernetes api to 1.12.3
  Gopkg.lock
  Gopkg.toml
Labels: in progress
