Repository Azure/acs-engine, pull requests merged in 2018-08, with the labels that each got.

#3593 Fix errors pointed out by "make test-style"
  cmd/deploy_test.go
  test/e2e/openshift/openshift_test.go
Labels: approved, in progress, lgtm, size/S

#3589 Update docs for some e2e environment variables
  docs/developers.md
Labels: approved, area/docs, in progress, lgtm, size/XS

#3595 restore exechealthz defs for back compat
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
Labels: approved, in progress, lgtm, size/XS

#3591 feat(vsts-ci.yaml): Scaffolding to support VHD image building in vsts
  .vsts-ci.yaml
Labels: approved, in progress, lgtm, size/XS

#3600 Kubernetes: acceleratedNetworking as a static whitelist
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: approved, in progress, lgtm, size/M

#3602 Ensure calico daemonset manifest passes validation in k8s 1.11
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
Labels: size/S

#3570 change outbound networking check to use more portable constructs
  parts/k8s/kubernetescustomscript.sh
Labels: approved, lgtm, size/XS

#3529 Kubernetes: enable docker health probe
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, size/M

#3598 Parallelizing all validate test cases
  pkg/api/agentPoolOnlyApi/v20180331/validate_test.go
  pkg/api/v20170131/validate_test.go
  pkg/api/v20170701/validate_test.go
  pkg/api/vlabs/validate_test.go
  pkg/helpers/helpers.go
Labels: size/XXL

#3584 Kubernetes containerd support configurable ContainerdDownloadURLBase and kubernetesPodInfraContainerSpec
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/types.go
Labels: approved, lgtm, size/S

#3604 add support for k8s v1.12.0-alpha.1
  .circleci/config.yml
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/k8s_versions.go
  pkg/api/common/versions.go
Labels: approved, in progress, size/L

#3607 add support for Kubernetes 1.9.10
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3611 update go-dev tools image
  .circleci/config.yml
  Makefile
  makedev.ps1
Labels: approved, in progress, lgtm, size/XS

#3610 Output VMSS cloud config settings.
  parts/iaasoutputs.t
  parts/k8s/kubernetesmastervars.t
Labels: in progress, size/XS

#3532 Updating omsagent yaml to use the latest yaml
  parts/k8s/addons/kubernetesmasteraddons-omsagent-daemonset.yaml
  pkg/acsengine/defaults.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, in progress, lgtm, size/L

#3618 Fix cni cleanup during kubelet start to be graceful & not loose any logs
  parts/k8s/kuberneteswindowssetup.ps1
Labels: lgtm, size/S

#3620 restore exechealthz defs for back compat
  pkg/acsengine/k8s_versions.go
  pkg/acsengine/k8s_versions_test.go
Labels: approved, in progress, lgtm, size/XS

#3623 Kubernetes: Remove unnecessary ARM vars
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  pkg/acsengine/addons.go
  pkg/api/types.go
  pkg/api/types_test.go
Labels: approved, in progress, lgtm, size/M

#3628 add support for Kubernetes 1.11.2
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3627 Kubernetes: variables --> parameters
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: approved, in progress, lgtm, size/L

#3635 Add mboersma to OWNERS file
  OWNERS
Labels: approved, in progress, lgtm, size/XS

#3633 Kubernetes: print kernel version during E2E
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/M

#3637 update ubuntu image to 16.04.201808060
  pkg/acsengine/defaults.go
Labels: in progress, size/XS

#3631 (docs): add available docker versions
  docs/clusterdefinition.md
Labels: approved, in progress, lgtm, size/XXL

#3641 Kubernetes: simplify addons implementation
  pkg/acsengine/addons.go
  pkg/acsengine/artifacts.go
  pkg/acsengine/defaults.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/validate.go
Labels: approved, in progress, size/XXL

#3648 Kubernetes: only enable blobfuse drivers on k8s 1.8 and above
  pkg/acsengine/addons.go
Labels: in progress, size/XS

#3652 Kubernetes: Enable ILB probe
  parts/k8s/kubernetesmasterresources.t
Labels: approved, in progress, lgtm, size/XS

#3649 Kubernetes: just use the ARM parameters
  docs/extensions.md
  examples/scale-up/kubernetes_template.json
  examples/scale-up/kubernetes_update_template.json
  parts/k8s/kubeconfig.json
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesjumpboxcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/engine.go
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_master_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_template.json
Labels: approved, in progress, lgtm, size/XXL

#3647 Deprecate ACS v1 classic mode support
  README.md
  README_zh-CN.md
  cmd/deploy.go
  cmd/generate.go
  cmd/generate_test.go
  cmd/scale.go
  cmd/scale_test.go
  examples/classic/README.md
  examples/classic/kubernetes.classic.json
  examples/classic/kubernetes.classic.rbac.json
  examples/classic/kubernetes.classic.windows.json
  examples/classic/kubernetes.classic.windows.json.env
  parts/classicparams.t
  parts/dcos/bstrap/bootstrapparams.t
  parts/dcos/bstrap/dcosbase.t
  parts/dcos/dcosbase.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/masteroutputs.t
  parts/masterparams.t
  parts/swarm/swarmagentresourcesclassic.t
  parts/swarm/swarmmastervars.t
  pkg/acsengine/const.go
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/params.go
  pkg/acsengine/template_generator.go
  pkg/api/vlabs/types.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, in progress, lgtm, size/XXL

#3617 get FD count for managed disk based on region
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
Labels: approved, in progress, lgtm, missing test, size/S

#3612 harden SSH: kex/ciphers/MACS + disable X11 forwarding
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/sshd_config
  pkg/acsengine/const.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/M

#3646 Kubernetes: ensure ARM operations have appropriate timeout value
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/acsengine/tenantid.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/deploymentError.go
  pkg/operations/deletevm.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, in progress, size/M

#3634 Enable DNS tests when windows nodes are present
  .circleci/config.yml
  examples/e2e-tests/kubernetes/windows/hybrid/definition.json
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/dns-liveness.yaml
  test/e2e/kubernetes/workloads/validate-dns.yaml
Labels: approved, lgtm, size/L

#3661 Revert "get FD count for managed disk based on region"
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
Labels: approved, in progress, size/S

#3660 Updating Azure-CNI to v1.0.11 for Windows
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/S

#3656 Errors parsing templates (parts/*) are ignored instead of raised
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/S

#3650 Add Packer
  .gitignore
  .vsts-ci.yaml
  Makefile
  packer.mk
  packer/cleanup-vhd.sh
  packer/init-variables.sh
  packer/install-dependencies.sh
  packer/settings-example.json
  packer/vhd-image-builder.json
Labels: approved, in progress, size/L

#3642 refactor CSE to separate installs
  docs/kubernetes/troubleshooting.md
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/const.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, size/XXL

#3672 Fix packer script path
  packer.mk
Labels: in progress, size/XS

#3675 chmod +x packer init-variables script
  packer.mk
  packer/init-variables.sh
  packer/install-dependencies.sh
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, size/XXL

#3676 Packer scripts Linux line endings
  packer/cleanup-vhd.sh
  packer/settings-example.json
  packer/vhd-image-builder.json
Labels: in progress, size/L

#3665 Fix the issue that the VMSS upgrading doesn't work if the topology do…
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: approved, in progress, size/M

#3614 Docs - simplifying Windows walkthrough
  docs/kubernetes/windows-details.md
  docs/kubernetes/windows.md
  examples/windows/kubernetes-wincni.json
  examples/windows/kubernetes.json
Labels: approved, in progress, lgtm, size/XXL

#3683 container registry proxy change for azure china cloud
  pkg/acsengine/defaults.go
Labels: approved, lgtm, size/XS

#3682 Improve VHD VSTS pipeline output URL
  .vsts-ci.yaml
  packer.mk
  packer/install-dependencies.sh
Labels: approved, awaiting review, in progress, lgtm, size/XS

#3686 Remove dcos e2e from circleci
  .circleci/config.yml
Labels: approved, in progress, lgtm, size/M

#3644 Scale down shouldn't depend on VM index
  cmd/scale.go
Labels: approved, in progress, lgtm, size/XS

#3679 Kubernetes: remove static allowed vals array for agent pool count
  parts/agentparams.t
Labels: approved, in progress, lgtm, size/XS

#3680 Golden image multiple k8s versions
  packer/install-dependencies.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastervars.t
Labels: approved, awaiting review, in progress, lgtm, size/M

#3674 Kubernetes: Azure CNI network monitor agents configuration errata
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/kubernetesagentcustomdata.yml
Labels: approved, in progress, lgtm, size/XS

#3639 Allow kube-proxy to run regardless of any node taint
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
Labels: approved, in progress, lgtm, size/XS

#3698 Kubernetes: Ubuntu 16.04.201808140
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3664 Kubernetes E2E: container networking tests
  test/e2e/config/config.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: approved, in progress, lgtm, size/L

#3688 Add dkms to manage nvidia gpu kmod compliation across different linux kernels
  parts/k8s/kubernetesagentcustomdata.yml
  pkg/acsengine/engine.go
Labels: approved, in progress, size/S

#3696 Small fixes in golden image
  packer/install-dependencies.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, lgtm, size/S

#3699 suspend openshift certgen go-bindata generation
  pkg/openshift/certgen/release39/templates/templates.go
  pkg/openshift/certgen/unstable/templates/templates.go
Labels: approved, in progress, size/XS

#3700 Kubernetes CSE: add func to ensure executable download
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, lgtm, size/S

#3706 add support for Kubernetes 1.10.7
  pkg/api/common/versions.go
Labels: approved, in progress, lgtm, size/XS

#3684 k8s 1.12 issue workaround
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3703 bump kms plugin version; fix for sovereign cloud
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: approved, in progress, lgtm, size/XS

#3671 Add AKS distro
  pkg/acsengine/defaults.go
  pkg/api/const.go
Labels: approved, in progress, size/S

#3701 Remove old files
  examples/scale-up/README.md
  examples/scale-up/kubernetes_orignal_params.json
  examples/scale-up/kubernetes_scale_up_params.json
  examples/scale-up/kubernetes_template.json
  examples/scale-up/kubernetes_update_template.json
  test/user.env.example
Labels: approved, in progress, size/XXL

#3573 Rework the way to parse --set flag values
  cmd/generate.go
  cmd/generate_test.go
  pkg/acsengine/transform/apimodel_merger.go
  pkg/acsengine/transform/apimodel_merger_test.go
Labels: approved, in progress, lgtm, size/L

#3713 Fix az command in day2-operations
  docs/kubernetes-day2-operations.md
Labels: approved, area/docs, lgtm, size/XS

#3711 Document orchestrator release and version
  docs/clusterdefinition.md
Labels: approved, area/docs, kind/documentation, orchestrator/k8s, size/S

#3710 updated DC/OS doc to point to the forked project
  docs/dcos.md
Labels: approved, area/docs, in progress, kind/documentation, lgtm, size/XS

#3704 Add extension for Windows patching at deployment
  extensions/windows-patches/README.md
  extensions/windows-patches/v1/installPatches.ps1
  extensions/windows-patches/v1/supported-orchestrators.json
  extensions/windows-patches/v1/template-link.json
  extensions/windows-patches/v1/template.json
Labels: approved, do-not-merge/hold, in progress, size/L

#3708 Check if software is already installed during provisioning
  packer/install-dependencies.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/L

#3722 rev Azure CNI version to v1.0.11 for Linux
  pkg/acsengine/defaults.go
Labels: approved, in progress, lgtm, size/XS

#3720 add all supported k8s versions to golden image
  .vsts-ci.yaml
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/S

#3724 Handle multiple CNI versions in golden image
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/M

#3716 Kubernetes: CSE errata
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3734 Docs: Ingress routing in mixed OS cluster
  docs/kubernetes/mixed-cluster-ingress.md
  docs/kubernetes/windows.md
Labels: approved, in progress, lgtm, size/L

#3721 Kubernetes: Use AKS curated OS images by default
  docs/clusterdefinition.md
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine.go
  pkg/acsengine/params.go
Labels: approved, in progress, lgtm, size/M

#3741 standardize ARM ops timeout to 2.5 hours
  cmd/deploy.go
  cmd/scale.go
  cmd/upgrade.go
  pkg/acsengine/tenantid.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/const.go
  pkg/armhelpers/deploymentError.go
  pkg/operations/deletevm.go
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, lgtm, size/S

#3742 only hold walinux during VHD image creation
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/S

#3685 Add support for k8s 1.12.0-beta.0
  pkg/api/common/versions.go
Labels: approved, do-not-merge/hold, in progress, lgtm, size/XS

#3744 Creating kube manifest dirs on node provision.
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
Labels: approved, in progress, lgtm, size/XS

#3743 enable pod priority for kubelet
  pkg/acsengine/defaults-kubelet.go
Labels: approved, in progress, lgtm, size/XS

#3757 set remaining ARM context timeouts to 2.5 hours
  pkg/armhelpers/azureclient.go
Labels: approved, in progress, lgtm, size/S

#3751 CSE: Stop waiting for cloud-init runcmd
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  parts/k8s/kubernetesprovisionsource.sh
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults.go
  pkg/acsengine/params_k8s.go
Labels: approved, in progress, lgtm, size/L

#3758 Minor if else optimization in the kubernetes base template
  parts/k8s/kubernetesbase.t
Labels: approved, in progress, lgtm, size/XS

#3761 Fix swapped username/password in Windows tutorial
  docs/kubernetes/windows.md
Labels: approved, in progress, lgtm, size/XS

#3759 GPU config as CSE implementation
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/L

#3768 Check for nil before using osPublisher
  cmd/scale.go
Labels: size/XS

#3736 Support for kubernetes clusters with user assigned msi
  Gopkg.lock
  cmd/deploy.go
  examples/kubernetes-msi-userassigned/kube-vma.json
  examples/kubernetes-msi-userassigned/kube-vmss.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/template_generator.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/vlabs/types.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/graph.go
  pkg/armhelpers/interfaces.go
  pkg/armhelpers/mockclients.go
  pkg/armhelpers/msi.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/userassignedidentities.go
  vendor/github.com/Azure/azure-sdk-for-go/services/preview/msi/mgmt/2015-08-31-preview/msi/version.go
Labels: approved, in progress, lgtm, size/XXL

#3453 Availability zone support for k8s
  docs/clusterdefinition.md
  examples/e2e-tests/kubernetes/zones/definition.json
  parts/agentparams.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/params.go
  pkg/acsengine/template_generator.go
  pkg/api/const.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/types_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/persistentvolume/persistentvolume.go
  test/e2e/kubernetes/persistentvolumeclaims/persistentvolumeclaims.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/workloads/pod-pvc.yaml
  test/e2e/kubernetes/workloads/pvc-premium.yaml
Labels: approved, in progress, size/XL

#3735 Documentation for Container monitoring addon
  docs/containermonitoringaddon.md
Labels: size/M

#3772 E2E: retain clusters if fail configuration
  .circleci/config.yml
Labels: in progress, size/S

#3753 Fix kubeletConfig for Windows agent nodes
  examples/windows/README.md
  examples/windows/kubernetes-hyperv.json
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/template_generator.go
Labels: do-not-merge/hold, in progress, size/L

#3745 Add new Azure client from a tenant
  pkg/armhelpers/azureclient.go
Labels: approved, in progress, lgtm, size/S

#3717 Adding E2E network policy tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/policies/client-one-deny-egress-policy.yaml
  test/e2e/kubernetes/workloads/policies/client-one-deny-ingress-policy.yaml
Labels: size/L

#3779 Revert "Allow kube-proxy to run regardless of any node taint (#3639)"
  parts/k8s/addons/kubernetesmasteraddons-kube-proxy-daemonset.yaml
Labels: approved, in progress, lgtm, size/XS

#3764 Add build metadata to VHD
  .vsts-ci.yaml
  packer/install-dependencies.sh
  packer/vhd-image-builder.json
Labels: approved, in progress, lgtm, size/S

#3774 bool ARM params need toLower
  parts/k8s/kubernetesmastervars.t
Labels: approved, in progress, kind/bug, lgtm, size/XS

#3782 Add k8s health monitor script for docker and kubelet
  parts/k8s/health-monitor.sh
  parts/k8s/kubernetes_mountetcd.sh
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesconfigs.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastergenerateproxycertscript.sh
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesprovisionsource.sh
  parts/k8s/setup-custom-search-domains.sh
  pkg/acsengine/const.go
  pkg/acsengine/template_generator.go
Labels: approved, in progress, lgtm, size/L

#3781 CSE: Remove outbound internet access requirement for VHD installs
  packer/install-dependencies.sh
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesinstalls.sh
Labels: approved, in progress, lgtm, size/M
