Repository Azure/acs-engine, pull requests merged in 2018-07, with the labels that each got.

#3397 Kubernetes: enable upgrade from 1.10 to 1.11
  pkg/operations/kubernetesupgrade/upgradecluster.go
Labels: approved, in progress, size/XS

#3388 Add support for k8s 1.9.9
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3392 Add bash completion for commands and arguments
  cmd/root.go
  docs/acsengine.md
Labels: approved, lgtm, size/S

#3400 fix doc table
  docs/clusterdefinition.md
Labels: approved, in progress, size/XS

#3387 Use errgroup instead of counting goroutines
  glide.lock
  glide.yaml
  pkg/acsengine/pki.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTING.md
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/README.md
  vendor/golang.org/x/sync/codereview.cfg
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/errgroup_example_md5all_test.go
  vendor/golang.org/x/sync/errgroup/errgroup_test.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/golang.org/x/sync/semaphore/semaphore_bench_test.go
  vendor/golang.org/x/sync/semaphore/semaphore_example_test.go
  vendor/golang.org/x/sync/semaphore/semaphore_test.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/golang.org/x/sync/singleflight/singleflight_test.go
  vendor/golang.org/x/sync/syncmap/map.go
  vendor/golang.org/x/sync/syncmap/map_bench_test.go
  vendor/golang.org/x/sync/syncmap/map_reference_test.go
  vendor/golang.org/x/sync/syncmap/map_test.go
Labels: approved, size/XXL

#3390 changes to fix issue #2312
  parts/k8s/addons/kubernetesmaster-audit-policy.yaml
  pkg/acsengine/addons.go
  pkg/acsengine/defaults-apiserver.go
Labels: approved, in progress, lgtm, size/S

#3386 Cleanup error usage
  cmd/dcos-upgrade.go
  cmd/deploy.go
  cmd/generate.go
  cmd/root.go
  cmd/scale.go
  cmd/upgrade.go
  glide.lock
  glide.yaml
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/tenantid.go
  pkg/api/apiloader.go
  pkg/api/common/helper.go
  pkg/api/common/net.go
  pkg/api/orchestrators.go
  pkg/api/strictjson.go
  pkg/armhelpers/azureclient.go
  pkg/armhelpers/utils/util.go
  pkg/operations/cordondrainvm.go
  pkg/operations/deletevm.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/bench_test.go
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/errors_test.go
  vendor/github.com/pkg/errors/example_test.go
  vendor/github.com/pkg/errors/format_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/pkg/errors/stack_test.go
Labels: approved, lgtm, size/XXL

#3382 Bring the coverage of vlabs/validate to 90%
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: approved, lgtm, size/XL

#3411 fix documented default for enableAggregatedAPIs
  docs/clusterdefinition.md
Labels: approved, in progress, lgtm, size/XS

#3410 update azure-npm to version v0.0.3
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
Labels: approved, lgtm, size/XS

#3407 Adding test for and fixing daemonsets that should not run on Windows
  parts/k8s/addons/azure-cni-networkmonitor.yaml
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-calico-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-flannel-daemonset.yaml
  parts/k8s/addons/kubernetesmasteraddons-kube-rescheduler-deployment.yaml
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm, size/S

#3419 remove version check from k8s e2e
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/node/node.go
Labels: approved, in progress, lgtm, size/S

#3344 Unit tests
  cmd/root.go
  cmd/root_test.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults-kubelet_test.go
  pkg/acsengine/defaults-scheduler_test.go
  pkg/acsengine/mocks.go
  pkg/acsengine/output.go
  pkg/acsengine/output_test.go
  pkg/operations/kubernetesupgrade/upgradecluster_test.go
Labels: approved, awaiting review, in progress, lgtm, size/L

#3424 long-term DNS livenessProbe tests for soak cluster
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/S

#3423 Remove DenyEscalatingExec admission controller from default list
  docs/clusterdefinition.md
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
Labels: approved, in progress, lgtm, size/S

#3425 E2E cleanup: "acse-test-infrastructure" is too long
  test/e2e/cleanup.sh
Labels: approved, in progress, size/XS

#3422 Nvidia device plugin updates for 1.11
  parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  pkg/acsengine/k8s_versions.go
Labels: in progress, size/XS

#3431 Starting Windows troubleshooting steps
  docs/kubernetes/troubleshooting.md
  docs/kubernetes/windows.md
Labels: in progress, windows

#3428 Kubernetes E2E: optimized HPA test
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#3430 Fix KMS in multi api-server
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#3401 Kubernetes: install blobfuse during CSE
  parts/k8s/kubernetescustomscript.sh
  parts/k8s/kubernetesprovisionsource.sh
Labels: approved, in progress, size/XS

#3437 K8s E2E: triage non-working KMS test implementation
  .circleci/config.yml
Labels: in progress

#3402 Reenable azurefile test
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress, size/XS

#3441 Kubernetes CSE: higher timeout, more retries for dpkg -i
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#3442 Kubernetes E2E: nil panic vector
  test/e2e/engine/template.go
Labels: in progress

#3433 Kubernetes: Azure CNI v1.0.7
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/api/const.go
Labels: in progress

#3440 Update clusterKeyVaultName for kv and sa
  .circleci/config.yml
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#3429 Adding e2e sample for kubenet+wincni and adding DNS back to e2e tests
  examples/windows/README.md
  examples/windows/kubernetes-wincni.json
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#3438 Fix the network blip caused during network creation/deletion
  parts/k8s/kuberneteswindowssetup.ps1
Labels: windows

#3459 Update kms plugin image tag
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: in progress

#3464 Add support for k8s 1.8.15
  pkg/api/common/versions.go
Labels: in progress

#3417 Do not deploy AKS Billing extension for national clouds
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentresourcesvmss.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/k8s/kuberneteswinagentresourcesvmss.t
  pkg/acsengine/template_generator.go
Labels: size/S

#3461 Add manual steps for powershell remoting.
  docs/kubernetes/troubleshooting.md
  docs/kubernetes/windows.md
Labels: in progress

#3335 Mount audit log file to disk
  parts/k8s/manifests/kubernetesmaster-kube-apiserver.yaml
  pkg/acsengine/defaults-apiserver.go
Labels: size/XS

#3470 Adding more descriptions and clarifications to Windows tests
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: in progress

#3449 Activate Accelerated Networking per default
  pkg/acsengine/defaults.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
  pkg/api/vlabs/validate.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: in progress

#3483 Do not enable AcceleratedNetworkingEnabled by default on upgrade
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
Labels: in progress

#3480 Fix oreg_url to work for our CI tests
  parts/openshift/release-3.9/openshiftmasterscript.sh
  parts/openshift/unstable/openshiftmasterscript.sh
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/release39/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/release39/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/release39/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/release39/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/release39/templates/master/tmp/bootstrapconfigs/master-config.yaml
  pkg/openshift/certgen/unstable/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/master/etc/origin/master/master-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/ansible/azure-local-master-inventory.yml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/compute-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/infra-config.yaml
  pkg/openshift/certgen/unstable/templates/master/tmp/bootstrapconfigs/master-config.yaml
Labels: in progress

#3491 Kubernetes: retry modprobe, and specific error
  parts/k8s/kubernetescustomscript.sh
Labels: in progress, orchestrator/k8s

#3490 Do not enable accelerated networking for scale
  cmd/deploy.go
  cmd/generate.go
  cmd/scale.go
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/template_generator.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: in progress

#3455 install blobfuse & smb flexvol drivers in provision time
  parts/k8s/kubernetescustomscript.sh
Labels: in progress

#3495 add support for Kubernetes v1.11.1
  pkg/api/common/versions.go
Labels: in progress

#3497 NVIDIA device plugin limits and requests
  parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/defaults.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
Labels: in progress

#3504 Kubernetes E2E: check for nil node InternalIP
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#3509 (fix) nvidia resource limits "classic mode"
  pkg/acsengine/template_generator.go
Labels: in progress

#3498 Add keyvault-flexvolume addon
  docs/clusterdefinition.md
  examples/addons/keyvault-flexvolume/README.md
  examples/addons/keyvault-flexvolume/kubernetes-keyvault-flexvolume.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-disabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/addons-enabled.json
  parts/k8s/addons/kubernetesmasteraddons-keyvault-flexvolume-installer.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/addons.go
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/params_k8s.go
  pkg/acsengine/template_generator.go
  pkg/acsengine/testdata/addons/kubernetes.json
  pkg/api/const.go
  pkg/api/types.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#3518 E2E cleanup: allows AKS clusters to stick around
  test/e2e/cleanup.sh
Labels: in progress

#3517 Kubernetes GPU: ensure nvidia drivers install after docker is installed
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetescustomscript.sh
  pkg/acsengine/engine.go
Labels: in progress, kind/bug, orchestrator/k8s

#3521 update prereqs in developer docs
  docs/developers.md
Labels: in progress

#3524 Revert "Commit minor changes to generated code"
  pkg/openshift/certgen/release39/templates/bindata.go
  pkg/openshift/certgen/unstable/templates/bindata.go
Labels: in progress

#3525 sync Azure NPM version with Azure CNI version
  parts/k8s/addons/kubernetesmasteraddons-azure-npm-daemonset.yaml
Labels: size/XS

#3519 Get sub from azure CLI when not provided
  Gopkg.lock
  Gopkg.toml
  cmd/root.go
  cmd/root_test.go
  pkg/helpers/helpers.go
  vendor/gopkg.in/ini.v1/.gitignore
  vendor/gopkg.in/ini.v1/.travis.yml
  vendor/gopkg.in/ini.v1/LICENSE
  vendor/gopkg.in/ini.v1/Makefile
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/ini.go
  vendor/gopkg.in/ini.v1/key.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/gopkg.in/ini.v1/section.go
  vendor/gopkg.in/ini.v1/struct.go
Labels: size/XXL

#3527 Installing vendored go-bindata binaries
  .circleci/config.yml
  Gopkg.lock
  Gopkg.toml
  Makefile
  vendor/github.com/go-bindata/go-bindata/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/LICENSE
  vendor/github.com/go-bindata/go-bindata/Makefile
  vendor/github.com/go-bindata/go-bindata/README.md
  vendor/github.com/go-bindata/go-bindata/asset.go
  vendor/github.com/go-bindata/go-bindata/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/config.go
  vendor/github.com/go-bindata/go-bindata/convert.go
  vendor/github.com/go-bindata/go-bindata/debug.go
  vendor/github.com/go-bindata/go-bindata/doc.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/release.go
  vendor/github.com/go-bindata/go-bindata/restore.go
  vendor/github.com/go-bindata/go-bindata/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/testdata/symlinkFile/file1
  vendor/github.com/go-bindata/go-bindata/testdata/symlinkParent/symlinkTarget
  vendor/github.com/go-bindata/go-bindata/testdata/symlinkRecursiveParent/symlinkTarget
  vendor/github.com/go-bindata/go-bindata/toc.go
Labels: size/XXL

#3531 Pump k8s-azure-kms version
  parts/k8s/artifacts/kubernetesazurekms.service
Labels: approved, in progress, size/XS

#3482 removed datadisk to allow scale after upgrade
  pkg/acsengine/transform/transform.go
  pkg/acsengine/transform/transformtestfiles/k8s_agent_upgrade_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_scale_template.json
  pkg/acsengine/transform/transformtestfiles/k8s_vnet_scale_template.json
Labels: in progress, size/M

#3535 Kubernetes only: prefer pulling directly from gcr.io and docker.io
  docs/clusterdefinition.md
  docs/kubernetes/k8s-developers.md
  examples/addons/cluster-autoscaler/README.md
  examples/scale-up/kubernetes_orignal_params.json
  examples/scale-up/kubernetes_scale_up_params.json
  extensions/prometheus-grafana-k8s/v1/prometheus_values.yaml
  jenkins/Jenkinsfile.azure.kubernetes
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/cuda-vector-add.yaml
Labels: in progress, size/M

#3539 Retire Swarm E2E for PR test coverage
  .circleci/config.yml
Labels: approved, in progress, size/M

#3540 DCOS E2E: only do az vm list for k8s
  test/e2e/runner/cli_provisioner.go
Labels: approved, in progress, size/S

#3552 Kubernetes E2E: --image-pull-policy=IfNotPresent for kubectl run commands
  test/e2e/kubernetes/deployment/deployment.go
Labels: in progress, size/XS

#3553 revert --image-pull-policy=IfNotPresent for win
  test/e2e/kubernetes/deployment/deployment.go
Labels: approved, in progress, size/XS

#3474 DOCUMENTATION: Fix Documented Default Value for clusterSubnet
  docs/clusterdefinition.md
  pkg/acsengine/defaults.go
Labels: in progress, size/XS

#3282 Change dns healthcheck to look at external domain
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
Labels: size/XS

#3530 removing rbac error checking from merge fn
  pkg/api/agentPoolOnlyApi/v20180331/merge.go
  pkg/api/agentPoolOnlyApi/v20180331/merge_test.go
Labels: in progress, size/L

#3496 Reenable AzureFile tests for Windows on K8s 1.11.1, resolves #3439
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, lgtm

#3271 fix an issue where networkPlugin was not defined correctly when using calico or cilium
  examples/networkpolicy/README.md
Labels: in progress, size/M

#3555 print out ubuntu ver in e2e
  test/e2e/kubernetes/kubernetes_test.go
Labels: approved, in progress, size/S

#3471 Adding 'make dev' equivalent for Windows
  README.md
  makedev.ps1
Labels: in progress

#3551 Kubernetes: update to Azure CNI v1.0.10
  pkg/acsengine/defaults.go
Labels: approved, in progress, size/XS

#3473 Docs: Update user guide list to include Windows, update description of clusters
  README.md
  docs/kubernetes.md
Labels: in progress, size/S

#3559 Add support for Kubernetes v1.10.6
  pkg/api/common/versions.go
Labels: approved, in progress, size/XS

#3560 Kubernetes: update ubuntu image to 16.04.201807240
  pkg/acsengine/defaults.go
Labels: approved, in progress, size/XS

#3577 Add kubernetes1.11.json
  examples/kubernetes-releases/kubernetes1.11.json
Labels: approved, in progress, lgtm, size/M

#3578 Kubernetes: re-enable Azure CNI networking monitor by default
  pkg/acsengine/defaults.go
  pkg/acsengine/defaults_test.go
Labels: approved, in progress, size/S

#3556 OSA external API
  pkg/api/const.go
  pkg/api/converterfromosaapi.go
  pkg/api/converterfromosaapi_test.go
  pkg/api/convertertoosaapi.go
  pkg/api/convertertoosaapi_test.go
  pkg/api/osa/vlabs/types.go
  pkg/api/osa/vlabs/types_test.go
  pkg/api/types.go
Labels: approved, in progress, lgtm, size/XL

#3585 Fix validation when using keyvaultSecretRef
  cmd/deploy.go
Labels: approved, in progress, lgtm, size/XS

#3582 added a property for aks
  pkg/api/types.go
Labels: approved, in progress, lgtm, size/S

#3586 Autoscale api model
  pkg/api/types.go
  pkg/helpers/helpers.go
  pkg/helpers/helpers_test.go
Labels: in progress, size/S

#3588 Remove OCP 3.9 tests
  .circleci/config.yml
Labels: approved, lgtm, size/L

#3587 Fix a DCOS upgrade test case when ~/.azure/config exists
  cmd/dcos-upgrade_test.go
Labels: in progress, size/S

#3592 Add a README.md badge for code documentation
  README.md
Labels: approved, area/docs, in progress, lgtm, size/XS
