Repository Azure/acs-engine, pull requests merged in 2018-02, with the labels that each got.

#2240 E2E: don’t collect logs if soak test
  test/e2e/runner.go
Labels: in progress

#2242 Kubernetes 1.9.3 support
  examples/k8s-upgrade/v1.8.4.json.env
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/common/helper_test.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: awaiting review

#2243 Kubernetes 1.8.8 support
  examples/k8s-upgrade/README.md
  examples/k8s-upgrade/v1.7.9-hybrid.json.env
  examples/k8s-upgrade/v1.7.9-win.json.env
  examples/k8s-upgrade/v1.7.9.json.env
  pkg/acsengine/k8s_versions.go
  pkg/api/common/const.go
  pkg/api/orchestrators_test.go
  pkg/api/vlabs/validate.go
  pkg/api/vlabs/validate_test.go
Labels: awaiting review

#2230 Windows RS3 hot fix for k8s
  parts/k8s/kubernetesbase.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswindowssetup.ps1
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/types.go
Labels: in progress

#2245 Refine etcd sync between cloud init and cse
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2254 Always deliver an "enabled" value for an addon
  pkg/acsengine/defaults.go
Labels: in progress

#2241 enforce apt-get update warnings/errors retries
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#2255 Add single quotes around sp secret
  parts/k8s/kubernetesmastervars.t
Labels: in progress

#2253 --use-service-account-credentials=false if no rbac
  pkg/acsengine/const.go
Labels: in progress

#2259 Latest ubuntu image: 16.04.201801260
  parts/agentparams.t
  parts/masterparams.t
  pkg/acsengine/defaults.go
Labels: in progress

#2217 Kubernetes Tiller Addon: configuration to set max-history
  examples/e2e-tests/kubernetes/release/default/definition.json
  examples/e2e-tests/kubernetes/windows/definition.json
  parts/k8s/addons/kubernetesmasteraddons-tiller-deployment.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: awaiting review, kind/feature, orchestrator/k8s, size/small

#2261 freshen go-dev image
  .circleci/config.yml
  Makefile
  pkg/acsengine/engine.go
  pkg/acsengine/pki.go
  test/e2e/runner/cli_provisioner.go
Labels: in progress

#2266 - keeping original DeploymentOperationsListResult in DeploymentError
  pkg/armhelpers/deploymentError.go
  pkg/armhelpers/deploymentError_test.go
  pkg/operations/kubernetesupgrade/upgradeagentnode.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: in progress

#2267 untangle —authorization-mode from enableSecureKubelet
  pkg/acsengine/defaults-apiserver.go
  pkg/acsengine/defaults-apiserver_test.go
  pkg/acsengine/defaults-kubelet.go
  pkg/acsengine/defaults-kubelet_test.go
Labels: in progress

#2276 kubelet —cluster-domain is user-overridable
  docs/clusterdefinition.md
  pkg/acsengine/defaults-kubelet.go
Labels: in progress

#2279 E2E: service LB validations and pod Ready/NotReady
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
  test/e2e/kubernetes/service/service.go
Labels: in progress

#2291 E2E: HPA as a property of Deployments
  test/e2e/kubernetes/deployment/deployment.go
  test/e2e/kubernetes/kubernetes_test.go
Labels: in progress

#2289 ETE: svc URL validation: more time and avoid nil panic
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/service/service.go
Labels: in progress

#2292 New etcd versions and update default to v3.2.16
  pkg/acsengine/const.go
  pkg/api/vlabs/validate.go
Labels: in progress

#2277 More e2e tests
  examples/e2e-tests/kubernetes/kubernetes-config/addons-disabled.json
  examples/e2e-tests/kubernetes/kubernetes-config/clear-containers.json
  examples/e2e-tests/kubernetes/kubernetes-config/network-policy-none.json
  examples/e2e-tests/kubernetes/kubernetes-config/rbac-disabled.json
  examples/e2e-tests/kubernetes/release/default/definition.json
Labels: in progress

#2294 E2E Addons
  examples/e2e-tests/kubernetes/release/default/definition.json
  test/e2e/engine/template.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/pod/pod.go
Labels: awaiting review

#2305 ensure docker installs before ensure docker runs
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastercustomscript.sh
Labels: in progress

#2306 Update apimodel after upgrade
  cmd/upgrade.go
Labels: in progress

#2303 using --cluster-domain for kube-dns domain
  parts/k8s/addons/kubernetesmasteraddons-kube-dns-deployment.yaml
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kubernetesparams.t
  pkg/acsengine/engine.go
Labels: in progress

#2310 set kubelet defaults for --cgroups-per-qos & --enforce-node-allocatable
  docs/clusterdefinition.md
  pkg/acsengine/defaults-kubelet.go
Labels: in progress

#2219 Updates NVIDIA drivers installation
  docs/kubernetes/gpu.md
  pkg/acsengine/engine.go
Labels: in progress

#2315 Revert static IP allocation logic in Azure CNI, PR 1966.
  docs/kubernetes/features.md
  examples/e2e-tests/kubernetes/release/default/definition.json
  examples/vnet/kubernetesvnet-azure-cni.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesagentvars.t
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  pkg/acsengine/const.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
Labels: in progress

#2316 add restarts to nvidia drivers download in cloud-init
  examples/e2e-tests/kubernetes/gpu-enabled/definition.json
  parts/k8s/kubernetesagentcustomdata.yml
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  test/e2e/engine/template.go
  test/e2e/kubernetes/job/job.go
  test/e2e/kubernetes/kubernetes_test.go
  test/e2e/kubernetes/workloads/nvidia-smi.yaml
Labels: in progress

#2293 Support multiple AcsEngineClientIDs
  pkg/armhelpers/azureclient.go
Labels: in progress

#2321 Update docs to reflect current kubelet --read-only-port config
  docs/clusterdefinition.md
Labels: area/docs, in progress

#2325 fix quotation in etcd daemon args
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#2322 remove Windows + custom VNET validation error
  pkg/api/vlabs/validate.go
Labels: in progress

#2329 Reboot etcd fix
  parts/k8s/kubernetesmastercustomdata.yml
Labels: in progress

#2326 Private clusters
  docs/clusterdefinition.md
  docs/kubernetes/features.md
  examples/e2e-tests/kubernetes/kubernetes-config/private-cluster-single-master.json
  examples/e2e-tests/kubernetes/kubernetes-config/private-cluster.json
  parts/k8s/kubernetesagentresourcesvmas.t
  parts/k8s/kubernetesmastercustomdata.yml
  parts/k8s/kubernetesmasterresources.t
  parts/k8s/kubernetesmastervars.t
  parts/k8s/kuberneteswinagentresourcesvmas.t
  parts/masteroutputs.t
  pkg/acsengine/engine.go
  pkg/api/converterfromapi.go
  pkg/api/convertertoapi.go
  pkg/api/types.go
  pkg/api/vlabs/types.go
Labels: awaiting review

#2348 missing import
  pkg/acsengine/engine.go
Labels: in progress, kind/bug

#2344 Allow "v" prefix in orchestrator version and release
  pkg/api/common/helper.go
  pkg/api/common/helper_test.go
  pkg/api/vlabs/validate_test.go
Labels: awaiting review

#2330 Improve the instructions for AAD.
  docs/kubernetes/aad.md
Labels: in progress

#2353 Fix master resources merge conflict
  parts/k8s/kubernetesmasterresources.t
Labels: in progress

#2327 Use original FirstConsecutiveStaticIP during upgrade.
  cmd/deploy.go
  cmd/generate.go
  cmd/scale.go
  pkg/acsengine/defaults.go
  pkg/acsengine/engine.go
  pkg/acsengine/engine_test.go
  pkg/acsengine/transform/transform.go
  pkg/operations/kubernetesupgrade/upgrader.go
Labels: in progress

#2238 fix azure file dynamic provision permission issue
  parts/k8s/addons/kubernetesmasteraddons-azure-cloud-provider-deployment.yaml
  pkg/acsengine/addons.go
Labels: DO-NOT-MERGE, in progress

#2320 mount /sbin/apparmor_parser if PodSecurityPolicy is enabled
  parts/k8s/artifacts/kuberneteskubelet.service
  parts/k8s/kubernetesagentcustomdata.yml
  parts/k8s/kubernetesmastercustomdata.yml
  pkg/acsengine/engine.go
Labels: in progress

#2357 Allow a default k8s version for loading agentpool-only clusters
  pkg/api/apiloader.go
Labels: in progress, orchestrator/k8s

#2354 Private clusters iteration 2: change the server for the cluster kubeconfig
  parts/k8s/kubernetesmastercustomscript.sh
  parts/k8s/kubernetesmastervars.t
Labels: ready
